const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate=v=>{if(!v)return '-';try{return new Date(v).toLocaleString('ko-KR')}catch{return String(v)}};
const db={projects:[],features:[],devices:[],sources:[],companies:[],contacts:[],followups:[],distributionHistory:[],executions:[],tasks:[]};
let currentId=null,lastAnalysis=null,currentView='dash',activeCat='전체',syncMeta=null,syncing=false,connection={google:false,data:false,sales:false,tasks:false};

async function api(url,opts={}){const r=await fetch(url,{...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
async function authStatus(){const s=await api('/api/auth/status').catch(e=>({connected:false,error:e.message}));connection.google=!!s.connected;const html=s.connected?`<span class="tag green">Google 연결됨 · ${esc(s.user?.email||'')}</span> <button class="btn" onclick="logoutGoogle()">연결 해제</button>`:`<a class="btn primary" href="/api/auth/google">Google 연결</a><div class="muted" style="margin-top:6px">실제 Drive/Sheets 데이터를 보려면 Google 연결이 필요합니다.</div>`;if($('#authTop'))$('#authTop').innerHTML=html;if($('#authBox'))$('#authBox').innerHTML=html;return s}
async function logoutGoogle(){await api('/api/auth/logout',{method:'POST'}).catch(()=>{});location.reload()}
function current(){return db.projects.find(p=>p.id===currentId)}
function folderId(v=''){const m=String(v).match(/\/folders\/([A-Za-z0-9_-]+)/);return m?m[1]:''}
function statusOption(currentValue,items){return [...new Set([currentValue,...items].filter(Boolean))].map(v=>`<option ${v===currentValue?'selected':''}>${esc(v)}</option>`).join('')}
function sourceState(ok,label){return ok?`<span class="tag green">${esc(label)} 연결됨</span>`:`<span class="tag amber">${esc(label)} 연결 안 됨</span>`}
function syncBadge(){if(!syncMeta)return '<span class="tag amber">원본 동기화 전</span>';const good=['성공','부분 성공'].includes(syncMeta.status),cls=good?'green':'amber';return `<span class="tag ${cls}">원본 동기화 ${esc(syncMeta.status||'확인 필요')}</span><span class="muted"> ${esc(syncMeta.value||'')} · ${esc(fmtDate(syncMeta.updated_at))}${syncMeta.error?` · ${esc(syncMeta.error)}`:''}</span>`}
function categories(){return ['전체',...new Set(db.projects.map(p=>p.category||'기타').filter(Boolean))]}

async function bootstrap(){const auth=await authStatus();if(!auth.connected){renderAll();return}const results=await Promise.all([loadCentral(),loadSales(),loadTasks()]);renderAll();if(results[0]?.needsSync&&!syncing)syncProjectSources(true)}
async function loadCentral(){try{const d=await api('/api/live-data?action=bootstrap');db.projects=d.projects||[];db.features=d.features||[];db.devices=d.devices||[];db.sources=d.sources||[];db.executions=d.executions||[];syncMeta=d.syncState||null;connection.data=true;return d}catch(e){connection.data=false;db.projects=[];db.features=[];db.devices=[];db.sources=[];db.executions=[];syncMeta={status:'실패',value:'중앙 운영 데이터 연결 안 됨',error:e.message};return null}}
async function loadSales(){try{const d=await api('/api/live-sales');db.companies=d.companies||[];db.contacts=d.contacts||[];db.followups=d.followups||[];db.distributionHistory=d.distributionHistory||[];connection.sales=true}catch(e){connection.sales=false;db.companies=[];db.contacts=[];db.followups=[];db.distributionHistory=[]}}
async function loadTasks(){try{const d=await api('/api/work-tasks?action=list');db.tasks=d.tasks||[];connection.tasks=true}catch(e){connection.tasks=false;db.tasks=[]}}
async function syncProjectSources(silent=false){if(syncing)return;syncing=true;if(!silent){if($('#projectSourceState'))$('#projectSourceState').innerHTML='<span class="tag">2026년 팀그릿 업무진행 + 시스템개발팀 + 연결 자료 동기화 중...</span>';if($('#syncProjects'))$('#syncProjects').disabled=true}try{const d=await api('/api/live-data?action=sync',{method:'POST',body:'{}'});if(d.ok&&d.data){applyCentral(d.data);if(!silent)alert(`원본 동기화 완료: 프로젝트 ${d.projects}건 · 기능 ${d.features}건 · 장비 ${d.devices}건 · 원본 ${d.sources}건`)}else{await loadCentral();if(!silent)alert(d.error||'원본 자료 연결 안 됨')}}catch(e){await loadCentral();if(!silent)alert('원본 동기화 실패: '+e.message)}finally{syncing=false;if($('#syncProjects'))$('#syncProjects').disabled=false;renderAll()}}
function applyCentral(d){db.projects=d.projects||[];db.features=d.features||[];db.devices=d.devices||[];db.sources=d.sources||[];db.executions=d.executions||[];syncMeta=d.syncState||null;connection.data=true}
function renderAll(){if(currentView==='dash')renderDash();if(currentView==='projects')renderProjects();if(currentView==='sales')renderSales();if(currentView==='work')renderWork();if(currentView==='automation')renderAutomation()}
function hideAll(){['dashboard','projects','sales','work','automation','projectDetail'].forEach(id=>$('#'+id)?.classList.add('hidden'));document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'))}
function show(view){currentView=view;hideAll();const id={dash:'dashboard',projects:'projects',sales:'sales',work:'work',automation:'automation'}[view],nav={dash:'navDash',projects:'navProjects',sales:'navSales',work:'navWork',automation:'navAutomation'}[view];$('#'+id)?.classList.remove('hidden');$('#'+nav)?.classList.add('active');renderAll();authStatus();window.scrollTo({top:0,behavior:'auto'})}

function renderDash(){const active=db.projects.filter(p=>!['완료','완료됨','폐기됨'].includes(p.status)).length,pending=db.tasks.filter(t=>!['완료','완료됨'].includes(t.status)).length;$('#metrics').innerHTML=`<div class="metric"><b>${active}</b><span class="muted">진행 프로젝트</span></div><div class="metric"><b>${pending}</b><span class="muted">등록 업무</span></div><div class="metric"><b>${db.companies.length}</b><span class="muted">실제 영업 기업</span></div><div class="metric"><b>${db.sources.length}</b><span class="muted">연결 원본</span></div>`;$('#dashSources').innerHTML=`${sourceState(connection.data,'중앙 운영 데이터')} ${sourceState(connection.sales,'영업 운영 시트')} ${sourceState(connection.tasks,'업무 데이터')} ${syncBadge()}`;$('#dashProjects').innerHTML=connection.data?(db.projects.length?projectTable(db.projects):'<div class="empty">원본 동기화로 확인된 프로젝트가 아직 없습니다.</div>'):'<div class="notice">중앙 운영 데이터 연결 안 됨</div>';$('#dashTasks').innerHTML=connection.tasks?(db.tasks.length?taskTable(db.tasks.slice(0,8)):'<div class="empty">등록된 업무가 없습니다.</div>'):'<div class="notice">업무 데이터 연결 안 됨</div>';bindProjectRows()}
function projectTable(ps){return `<table class="table"><thead><tr><th>프로젝트</th><th>고객/대상</th><th>분류</th><th>상태</th><th>원본</th><th>업데이트</th></tr></thead><tbody>${ps.map(p=>`<tr data-project="${esc(p.id)}"><td><b>${esc(p.name)}</b></td><td>${esc(p.customer||'-')}</td><td>${esc(p.category||'기타')}</td><td>${esc(p.status||'확인 필요')}</td><td>${(p.sources||[]).length?`<span class="tag green">${p.sources.length}개</span>`:'<span class="tag amber">연결 안 됨</span>'}</td><td>${esc(fmtDate(p.updatedAt))}</td></tr>`).join('')}</tbody></table>`}
function bindProjectRows(){document.querySelectorAll('[data-project]').forEach(el=>el.onclick=()=>openProject(el.dataset.project))}
function renderProjects(){const ps=db.projects.filter(p=>activeCat==='전체'||p.category===activeCat);$('#projectSourceState').innerHTML=`${sourceState(connection.data,'TeamGRIT Ops 운영 데이터')} ${syncBadge()}`;$('#catTabs').innerHTML=categories().map(c=>`<button data-cat="${esc(c)}" class="${c===activeCat?'active':''}">${esc(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;renderProjects()});$('#projectList').innerHTML=connection.data?(ps.length?projectTable(ps):'<div class="empty">해당 분류에서 원본 근거가 확인된 프로젝트가 없습니다.</div>'):'<div class="notice">중앙 운영 데이터 연결 안 됨</div>';$('#sourceOverview').innerHTML=connection.data?sourceOverview():'<div class="notice">원본 데이터 연결 안 됨</div>';bindProjectRows()}
function sourceOverview(){const roots=['2026년 팀그릿 업무진행','시스템개발팀'];return `<div class="taskActions" style="margin-bottom:10px">${roots.map(r=>{const n=db.sources.filter(s=>s.root_source===r),ok=n.some(s=>s.status==='연결됨');return sourceState(ok,r)+` <span class="muted">${n.length}개 원본</span>`}).join(' ')}</div>${db.sources.length?`<table class="table"><thead><tr><th>원본</th><th>루트</th><th>상태</th><th>수정</th></tr></thead><tbody>${db.sources.slice(0,30).map(s=>`<tr><td>${s.url?`<a target="_blank" href="${esc(s.url)}">${esc(s.title)}</a>`:esc(s.title)}</td><td>${esc(s.root_source||'-')}</td><td>${esc(s.status||'연결 안 됨')}</td><td>${esc(fmtDate(s.modified_time))}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">아직 수집된 원본이 없습니다.</div>'}`}
async function saveProject(patch){const p=current();if(!p)return;try{const d=await api('/api/live-data?action=project',{method:'POST',body:JSON.stringify({id:p.id,...patch})});Object.assign(p,d.project);connection.data=true;return true}catch(e){alert('중앙 저장 실패: '+e.message);return false}}

function renderSales(){const el=$('#salesSourceState');if(el)el.innerHTML=sourceState(connection.sales,'영업 통합 운영 시트');if(!connection.sales){$('#salesMetrics').innerHTML='';$('#companyList').innerHTML='<div class="notice">영업 운영 시트 연결 안 됨</div>';$('#contactList').innerHTML='<div class="empty">실제 시트 연결 후 표시됩니다.</div>';$('#followupList').innerHTML='<div class="empty">실제 시트 연결 후 표시됩니다.</div>';return}const open=db.followups.filter(x=>!['완료','완료됨'].includes(x.status)).length;$('#salesMetrics').innerHTML=`<div class="metric"><b>${db.companies.length}</b><span class="muted">기업</span></div><div class="metric"><b>${db.contacts.length}</b><span class="muted">Contact</span></div><div class="metric"><b>${open}</b><span class="muted">후속 액션</span></div><div class="metric"><b>${db.distributionHistory.length}</b><span class="muted">자료 배포 이력</span></div>`;$('#companyList').innerHTML=db.companies.length?`<table class="table"><thead><tr><th>기업</th><th>파트너사</th><th>최종고객사</th><th>산업군</th><th>영업 온도</th><th>담당 영업</th></tr></thead><tbody>${db.companies.map(c=>`<tr><td><b>${esc(c.companyName||'확인 필요')}</b></td><td>${esc(c.partner||'-')}</td><td>${esc(c.endCustomer||'-')}</td><td>${esc(c.industry||'-')}</td><td>${esc(c.salesTemperature||'-')}</td><td>${esc(c.accountOwner||'확인 필요')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">실제 영업 시트에 기업 데이터가 없습니다.</div>';$('#contactList').innerHTML=db.contacts.length?`<table class="table"><thead><tr><th>기업</th><th>담당자</th><th>이메일</th><th>연락처</th></tr></thead><tbody>${db.contacts.map(c=>{const co=db.companies.find(x=>x.id===c.companyId);return `<tr><td>${esc(co?.companyName||'확인 필요')}</td><td><b>${esc(c.name||'확인 필요')}</b></td><td>${esc(c.email||'-')}</td><td>${esc(c.phone||'-')}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">실제 영업 시트에 Contact가 없습니다.</div>';$('#followupList').innerHTML=db.followups.length?`<table class="table"><thead><tr><th>기업</th><th>후속 액션</th><th>예정일</th><th>담당자</th><th>상태</th></tr></thead><tbody>${db.followups.map(a=>{const co=db.companies.find(x=>x.id===a.companyId);return `<tr><td>${esc(co?.companyName||'확인 필요')}</td><td><b>${esc(a.title||'확인 필요')}</b></td><td>${esc(a.dueDate||'확인 필요')}</td><td>${esc(a.owner||'확인 필요')}</td><td>${esc(a.status||'확인 필요')}</td></tr>`}).join('')}</tbody></table>`:'<div class="empty">등록된 후속 액션이 없습니다.</div>'}

function taskTable(tasks){return `<table class="table"><thead><tr><th>업무</th><th>프로젝트</th><th>담당자</th><th>기한</th><th>상태</th><th>출처</th></tr></thead><tbody>${tasks.map(t=>`<tr><td><b>${esc(t.title||'')}</b></td><td>${esc(t.project||'확인 필요')}</td><td>${esc(t.owner||'확인 필요')}</td><td>${esc(t.due_date||t.dueDate||'확인 필요')}</td><td>${esc(t.status||'예정')}</td><td>${t.source_url?`<a target="_blank" href="${esc(t.source_url)}">${esc(t.source||'원문')}</a>`:esc(t.source||'-')}</td></tr>`).join('')}</tbody></table>`}
function renderWork(){if($('#workSourceState'))$('#workSourceState').innerHTML=`${sourceState(connection.tasks,'업무 중앙 데이터')} ${syncBadge()} <span class="tag">기준: 2026년 팀그릿 업무진행 + 시스템개발팀 + 연결 자료</span>`;$('#registeredTasks').innerHTML=connection.tasks?(db.tasks.length?taskTable(db.tasks):'<div class="empty">아직 등록된 업무가 없습니다.</div>'):'<div class="notice">업무 데이터 연결 안 됨</div>'}
async function analyzeMemo(){const memo=$('#workMemo').value.trim();if(!memo)return alert('회의 메모나 업무 메모를 입력해 주세요.');$('#workCandidates').innerHTML='<div class="muted">두 기준 문서와 연결 자료를 읽어 업무 후보를 추출 중...</div>';const started=new Date().toISOString();try{const d=await api('/api/work-tasks?action=analyze',{method:'POST',body:JSON.stringify({memo})});if(d.error&&!(d.tasks||[]).length){$('#workCandidates').innerHTML=`<div class="notice">${esc(d.error)}</div>`;return}window.workCandidates=(d.tasks||[]).map((t,i)=>({...t,_i:i,approved:true}));$('#workCandidates').innerHTML=window.workCandidates.length?window.workCandidates.map((t,i)=>candidateCard(t,i)).join(''):'<div class="empty">근거가 확인된 업무 후보가 없습니다.</div>';$('#workModel').textContent=d.modelUsed?`사용 모델: ${d.modelUsed} · 확인 원본 ${d.sourceCount||0}개`:'모델: 연결 안 됨';await logExecution({action:'업무 후보 추출',model:d.modelUsed||'',status:'성공',startedAt:started})}catch(e){$('#workCandidates').innerHTML=`<div class="notice">업무 후보 생성 실패: ${esc(e.message)}</div>`;await logExecution({action:'업무 후보 추출',status:'실패',error:e.message,startedAt:started})}}
function candidateCard(t,i){return `<div class="task" data-candidate="${i}"><div class="taskHead"><label><input type="checkbox" class="candidateApprove" data-i="${i}" checked> 등록 승인</label><span class="tag blue">후보</span></div><div class="field"><label>업무명</label><input class="candidateTitle" data-i="${i}" value="${esc(t.title||'')}"></div><div class="field"><label>프로젝트</label><input class="candidateProject" data-i="${i}" value="${esc(t.project||'')}" placeholder="확인 필요"></div><div class="field"><label>담당자</label><input class="candidateOwner" data-i="${i}" value="${esc(t.owner||'')}" placeholder="확인 필요"></div><div class="field"><label>기한</label><input class="candidateDue" data-i="${i}" value="${esc(t.dueDate||'')}" placeholder="확인 필요"></div><div class="muted">근거: ${esc(t.sourceEvidence||t.reason||'')} · Source ${esc((t.sourceIds||[]).join(', ')||'확인 필요')}</div></div>`}
async function registerApprovedTasks(){const items=window.workCandidates||[],tasks=items.map((t,i)=>({...t,approved:$(`.candidateApprove[data-i="${i}"]`)?.checked===true,title:$(`.candidateTitle[data-i="${i}"]`)?.value.trim()||'',project:$(`.candidateProject[data-i="${i}"]`)?.value.trim()||'',owner:$(`.candidateOwner[data-i="${i}"]`)?.value.trim()||'',dueDate:$(`.candidateDue[data-i="${i}"]`)?.value.trim()||''})).filter(t=>t.approved);if(!tasks.length)return alert('등록 승인한 업무가 없습니다.');try{const d=await api('/api/work-tasks?action=register',{method:'POST',body:JSON.stringify({tasks})});db.tasks=d.tasks||[];connection.tasks=true;$('#workCandidates').innerHTML='<div class="notice ok">승인한 업무를 중앙 업무표에 등록했습니다.</div>';window.workCandidates=[];renderWork()}catch(e){alert('업무 등록 실패: '+e.message)}}

function renderAutomation(){const recent=[...db.executions].reverse().slice(0,30);$('#automationSourceState').innerHTML=sourceState(connection.data,'Executions');$('#automationMetrics').innerHTML=`<div class="metric"><b>${db.executions.length}</b><span class="muted">기록된 실행</span></div><div class="metric"><b>${db.executions.filter(e=>String(e.status).includes('실패')).length}</b><span class="muted">실패</span></div><div class="metric"><b>${db.executions.filter(e=>e.model).length}</b><span class="muted">모델 기록</span></div>`;$('#automationHistory').innerHTML=recent.length?`<table class="table"><thead><tr><th>작업</th><th>모델</th><th>상태</th><th>오류</th><th>실행 시각</th></tr></thead><tbody>${recent.map(e=>`<tr><td><b>${esc(e.action||'-')}</b></td><td>${esc(e.model||'-')}</td><td>${esc(e.status||'-')}</td><td>${esc(e.error||'-')}</td><td>${esc(fmtDate(e.finished_at||e.started_at))}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">아직 중앙 실행 이력이 없습니다.</div>'}
async function logExecution(data){try{await api('/api/live-data?action=execution',{method:'POST',body:JSON.stringify({...data,project_id:data.projectId||'',project_name:data.projectName||'',started_at:data.startedAt||'',finished_at:new Date().toISOString(),output_type:data.outputType||'',file_url:data.fileUrl||'',error:data.error||'',model:data.model||'',status:data.status||'완료',action:data.action||''})});await loadCentral()}catch{}}

async function openProject(id){currentId=id;lastAnalysis=null;const p=current();if(!p)return;hideAll();$('#projectDetail').classList.remove('hidden');$('#navProjects').classList.add('active');$('#pCat').textContent=p.category||'기타';$('#pName').textContent=p.name;$('#pStatus').innerHTML=statusOption(p.status,['요구사항 협의','물품 구매 및 수령','개발중','검토 대기','진행 중','보류','완료','완료됨','폐기됨']);$('#pCategory').innerHTML=statusOption(p.category,['행사·마케팅','제품·UIUX','납품·PoC','개발','연구','문서·운영','기타']);$('#driveUrl').value=p.driveUrl||'';$('#figmaUrl').value=p.figmaUrl||'';$('#projectCentralState').innerHTML=`${sourceState(connection.data,'중앙 운영 데이터')} ${p.connectionStatus==='연결됨'?'<span class="tag green">원본 근거 있음</span>':'<span class="tag amber">원본 연결 안 됨</span>'}`;$('#analysis').innerHTML='<div class="empty">업무 요청을 입력하고 실제 Drive 자료를 분석하세요.</div>';$('#taskList').innerHTML='<div class="empty">아직 제안된 업무가 없습니다.</div>';$('#results').innerHTML='<div class="empty">이 화면에서는 현재 세션의 실행 결과를 표시합니다.</div>';renderProjectEvidence(p);await authStatus();if(p.driveFolderId)await loadFiles();else $('#driveFiles').innerHTML='<div class="empty">프로젝트별 Drive 폴더가 별도로 연결되지 않았습니다.</div>'}
function renderProjectEvidence(p){const src=p.sources||[],features=p.features||[],devices=p.devices||[];$('#projectSources').innerHTML=src.length?src.map(s=>`<div class="file">${s.url?`<a target="_blank" href="${esc(s.url)}"><b>${esc(s.title)}</b></a>`:`<b>${esc(s.title)}</b>`}<br><span class="muted">${esc(s.root_source||'')} · ${esc(s.status||'연결 안 됨')}</span></div>`).join(''):'<div class="empty">프로젝트에 연결된 원본 근거가 없습니다.</div>';$('#projectEntities').innerHTML=`<div class="split"><div><h4>기능</h4>${features.length?features.map(f=>`<div class="fact"><b>${esc(f.name)}</b>${f.description?`<br><span class="muted">${esc(f.description)}</span>`:''}</div>`).join(''):'<div class="empty">확인된 기능 없음</div>'}</div><div><h4>장비</h4>${devices.length?devices.map(d=>`<div class="fact"><b>${esc(d.name)}</b>${d.role?`<br><span class="muted">${esc(d.role)}</span>`:''}</div>`).join(''):'<div class="empty">확인된 장비 없음</div>'}</div></div>`}
async function loadFiles(){const p=current();if(!p?.driveFolderId)return;$('#driveFiles').innerHTML='<div class="muted">불러오는 중...</div>';try{const d=await api('/api/drive/list?folderId='+encodeURIComponent(p.driveFolderId));$('#driveFiles').innerHTML=(d.files||[]).length?d.files.map(f=>`<div class="file"><a target="_blank" href="${esc(f.webViewLink||'#')}"><b>${esc(f.name)}</b></a><br><span class="muted">${esc(f.mimeType||'')} · ${esc(fmtDate(f.modifiedTime))}</span></div>`).join(''):'<div class="empty">폴더에 파일이 없습니다.</div>'}catch(e){$('#driveFiles').innerHTML=`<div class="notice">Drive 자료 연결 안 됨 · ${esc(e.message)}</div>`}}
function renderAnalysis(a){const facts=(a?.facts||[]).map(f=>`<div class="fact"><span class="tag ${f.status==='확정'?'green':f.status==='질문'?'amber':''}">${esc(f.status||'')}</span><br><b>${esc(f.fact||'')}</b><br><span class="muted">${esc(f.source||'')}</span></div>`).join('');$('#analysis').innerHTML=`<div class="muted">${esc(a?.summary||'')}</div><div class="facts">${facts||'<div class="empty">확인된 사실 없음</div>'}</div>${(a?.missing||[]).length?`<div class="notice"><b>추가 확인 필요</b><br>${a.missing.map(esc).join('<br>')}</div>`:''}${a?.modelUsed?`<div class="muted">사용 모델: ${esc(a.modelUsed)}</div>`:''}`;$('#taskList').innerHTML=(a?.tasks||[]).length?a.tasks.map((t,i)=>`<div class="task" data-task-index="${i}"><div class="taskHead"><div><span class="tag blue">${esc(t.outputType||'Other')}</span><h4>${esc(t.title||'')}</h4></div><span class="tag">제안</span></div><p>${esc(t.reason||'')}</p><div class="taskActions"><button class="btn primary" onclick="executeTask(${i})">승인하고 실행</button><button class="btn" onclick="skipTask(${i})">제외</button></div></div>`).join(''):'<div class="empty">제안된 업무가 없습니다.</div>'}
async function analyzeDrive(){const p=current(),req=$('#requestText').value.trim();if(!p?.driveFolderId)return alert('먼저 실제 Drive 폴더를 연결해 주세요.');if(!req)return alert('업무 요청을 입력해 주세요.');const started=new Date().toISOString();$('#analysis').innerHTML='<div class="muted">실제 Drive 자료 분석 중...</div>';try{const d=await api('/api/drive/analyze',{method:'POST',body:JSON.stringify({folderId:p.driveFolderId,projectName:p.name,request:req,figmaUrl:p.figmaUrl||'',model:'auto'})});lastAnalysis=d.analysis||{};renderAnalysis(lastAnalysis);await logExecution({projectId:p.id,projectName:p.name,action:'Drive 분석',model:d.modelUsed||lastAnalysis.modelUsed||'',status:'성공',startedAt:started})}catch(e){$('#analysis').innerHTML='<div class="notice">분석 실패 · '+esc(e.message)+'</div>';$('#taskList').innerHTML='<div class="empty">제안 없음</div>';await logExecution({projectId:p.id,projectName:p.name,action:'Drive 분석',status:'실패',error:e.message,startedAt:started})}}
async function executeTask(i){const p=current(),t=lastAnalysis?.tasks?.[i];if(!p||!t)return;if(!confirm(`'${t.title}' 업무를 승인하고 실제 ${t.outputType} 결과물을 생성할까요?`))return;const started=new Date().toISOString();try{const d=await api('/api/tasks/execute',{method:'POST',body:JSON.stringify({approved:true,project:p,task:t,context:lastAnalysis,model:'auto'})});const result=`<div class="result"><span class="tag green">실행 완료</span><br><b>${esc(d.file?.name||t.title)}</b><br><span class="muted">${esc(d.modelUsed||'')}</span><br>${d.file?.url?`<a target="_blank" href="${esc(d.file.url)}">실제 Drive 파일 열기 →</a>`:''}</div>`;$('#results').insertAdjacentHTML('afterbegin',result);await logExecution({projectId:p.id,projectName:p.name,action:t.title,outputType:t.outputType,model:d.modelUsed||'',status:'성공',fileUrl:d.file?.url||'',startedAt:started})}catch(e){alert('실행 실패: '+e.message);await logExecution({projectId:p.id,projectName:p.name,action:t.title,status:'실패',error:e.message,startedAt:started})}}
function skipTask(i){document.querySelector(`[data-task-index="${i}"]`)?.remove()}

function bind(){$('#navDash').onclick=()=>show('dash');$('#navProjects').onclick=()=>show('projects');$('#navSales').onclick=()=>show('sales');$('#navWork').onclick=()=>show('work');$('#navAutomation').onclick=()=>show('automation');$('#backProjects').onclick=()=>show('projects');$('#syncProjects').onclick=()=>syncProjectSources(false);$('#analyzeMemo').onclick=analyzeMemo;$('#registerApproved').onclick=registerApprovedTasks;$('#analyzeDrive').onclick=analyzeDrive;$('#refreshDrive').onclick=loadFiles;$('#saveProjectLinks').onclick=async()=>{const driveUrl=$('#driveUrl').value.trim(),figmaUrl=$('#figmaUrl').value.trim(),ok=await saveProject({driveUrl,figmaUrl});if(ok){$('#driveState').innerHTML='<div class="notice ok">중앙 운영 데이터에 연결 정보를 저장했습니다. 다른 브라우저에서도 동일하게 표시됩니다.</div>';current().driveFolderId=folderId(driveUrl);if(current().driveFolderId)loadFiles()}};$('#pStatus').onchange=async e=>{if(await saveProject({status:e.target.value})){current().status=e.target.value}};$('#pCategory').onchange=async e=>{if(await saveProject({category:e.target.value})){$('#pCat').textContent=e.target.value;current().category=e.target.value}}}

window.logoutGoogle=logoutGoogle;window.executeTask=executeTask;window.skipTask=skipTask;window.show=show;window.renderAutomation=renderAutomation;window.db=db;
bind();bootstrap();
