const crypto=require('crypto');

const WORK_DOC_ID=process.env.TEAMGRIT_WORK_DOC_ID||'1Z5pJR4v7l9XzgVjALTcRPskkEYJoc_Ii5l6zA3gXqLI';
const SYSTEM_DEV_DOC_ID=process.env.SYSTEM_DEV_DOC_ID||'1TirSjrD8b2p07tHt5Gn9sOrQoJPigyFmwcgSbAXPSxc';
const MODEL=process.env.PROJECT_SYNC_GEMINI_MODEL||process.env.TASK_GEMINI_MODEL||'gemini-2.5-flash-lite';
const MAX_SOURCES=Math.max(20,Number(process.env.SOURCE_MAX_FILES||80));
const MAX_CORPUS_CHARS=Math.max(120000,Number(process.env.SOURCE_MAX_CORPUS_CHARS||450000));
const READABLE=new Set([
  'application/vnd.google-apps.document',
  'application/vnd.google-apps.spreadsheet',
  'application/vnd.google-apps.presentation',
  'application/vnd.google-apps.form'
]);
const FOLDER='application/vnd.google-apps.folder';

function clean(v){return v===undefined||v===null?'':String(v).trim()}
function safe(v,n=500){return clean(v).slice(0,n)}
function hash(v){return crypto.createHash('sha1').update(String(v)).digest('hex').slice(0,14)}
function stableId(prefix,v){return `${prefix}_${hash(v)}`}
function cleanJSON(t=''){return String(t).replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim()}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);if(r.status===204)return null;return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
function driveIdFromUrl(url=''){
  const s=String(url);
  const patterns=[/\/folders\/([A-Za-z0-9_-]+)/,/\/document\/d\/([A-Za-z0-9_-]+)/,/\/spreadsheets\/d\/([A-Za-z0-9_-]+)/,/\/presentation\/d\/([A-Za-z0-9_-]+)/,/\/forms\/d\/([A-Za-z0-9_-]+)/,/\/file\/d\/([A-Za-z0-9_-]+)/,/[?&]id=([A-Za-z0-9_-]+)/];
  for(const p of patterns){const m=s.match(p);if(m)return m[1]}return '';
}
function linkUrlsFromText(text=''){return [...new Set((String(text).match(/https?:\/\/[^\s<>()"']+/g)||[]).map(x=>x.replace(/[),.;]+$/,'')))]}
function sourceUrl(id,mime=''){
  if(mime==='application/vnd.google-apps.document')return `https://docs.google.com/document/d/${id}/edit`;
  if(mime==='application/vnd.google-apps.spreadsheet')return `https://docs.google.com/spreadsheets/d/${id}/edit`;
  if(mime==='application/vnd.google-apps.presentation')return `https://docs.google.com/presentation/d/${id}/edit`;
  if(mime==='application/vnd.google-apps.form')return `https://docs.google.com/forms/d/${id}/edit`;
  if(mime===FOLDER)return `https://drive.google.com/drive/folders/${id}`;
  return `https://drive.google.com/open?id=${id}`;
}
function extractDoc(doc){const text=[],links=[];function walk(content=[]){for(const b of content){for(const e of b.paragraph?.elements||[]){if(e.textRun?.content)text.push(e.textRun.content);const u=e.textRun?.textStyle?.link?.url;if(u)links.push(u)}for(const row of b.table?.tableRows||[])for(const cell of row.tableCells||[])walk(cell.content||[])}}walk(doc.body?.content||[]);for(const tab of doc.tabs||[])walk(tab.documentTab?.body?.content||[]);const joined=text.join('').trim();return {text:joined,links:[...new Set([...links,...linkUrlsFromText(joined)])]}}
function extractSheet(ss){const lines=[],links=[];for(const sh of ss.sheets||[]){lines.push(`# ${sh.properties?.title||'Sheet'}`);for(const block of sh.data||[])for(const row of block.rowData||[]){const vals=[];for(const cell of row.values||[]){let v=cell.formattedValue??cell.effectiveValue?.stringValue??cell.effectiveValue?.numberValue??cell.userEnteredValue?.stringValue??'';v=String(v);vals.push(v);if(cell.hyperlink)links.push(cell.hyperlink);for(const run of cell.textFormatRuns||[]){const u=run.format?.link?.uri;if(u)links.push(u)}links.push(...linkUrlsFromText(v))}if(vals.some(v=>clean(v)))lines.push(vals.join(' | '))}}const text=lines.join('\n').trim();return {text,links:[...new Set(links)]}}
function extractSlides(p){const out=[],links=[];for(const [i,s] of (p.slides||[]).entries()){out.push(`# Slide ${i+1}`);for(const pe of s.pageElements||[]){for(const el of pe.shape?.text?.textElements||[]){const t=el.textRun?.content||'';if(t)out.push(t);const u=el.textRun?.style?.link?.url;if(u)links.push(u);links.push(...linkUrlsFromText(t))}}}const text=out.join('\n').trim();return {text,links:[...new Set(links)]}}
function extractForm(f){const out=[f.info?.title||'Form'],links=[];for(const [i,it] of (f.items||[]).entries()){const t=`${i+1}. ${it.title||''}`;out.push(t);links.push(...linkUrlsFromText(t))}return {text:out.join('\n').trim(),links:[...new Set(links)]}}
async function meta(token,id){return gf(token,`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name,mimeType,modifiedTime,webViewLink,trashed`)}
async function listFolder(token,id){const q=encodeURIComponent(`'${id}' in parents and trashed=false`),out=[];let pageToken='';do{const url=`https://www.googleapis.com/drive/v3/files?q=${q}&pageSize=100&fields=nextPageToken,files(id,name,mimeType,modifiedTime,webViewLink,trashed)${pageToken?`&pageToken=${encodeURIComponent(pageToken)}`:''}`;const d=await gf(token,url);out.push(...(d.files||[]));pageToken=d.nextPageToken||''}while(pageToken&&out.length<MAX_SOURCES);return out.slice(0,MAX_SOURCES)}
async function readSource(token,m){if(m.mimeType==='application/vnd.google-apps.document')return extractDoc(await gf(token,`https://docs.googleapis.com/v1/documents/${m.id}?includeTabsContent=true`));if(m.mimeType==='application/vnd.google-apps.spreadsheet')return extractSheet(await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${m.id}?includeGridData=true`));if(m.mimeType==='application/vnd.google-apps.presentation')return extractSlides(await gf(token,`https://slides.googleapis.com/v1/presentations/${m.id}`));if(m.mimeType==='application/vnd.google-apps.form')return extractForm(await gf(token,`https://forms.googleapis.com/v1/forms/${m.id}`));return {text:'',links:[]}}
async function collectCorpus(token){
  const roots=[{id:WORK_DOC_ID,root:'2026년 팀그릿 업무진행'},{id:SYSTEM_DEV_DOC_ID,root:'시스템개발팀'}],queue=roots.map(x=>({...x,parentId:'',depth:0})),seen=new Set(),sources=[];
  while(queue.length&&sources.length<MAX_SOURCES){const item=queue.shift();if(!item?.id||seen.has(item.id))continue;seen.add(item.id);let m;try{m=await meta(token,item.id)}catch(e){sources.push({sourceId:stableId('source',item.id),fileId:item.id,title:item.root||item.id,mimeType:'',url:sourceUrl(item.id),parentSourceId:item.parentId?stableId('source',item.parentId):'',rootSource:item.root,status:'연결 안 됨',modifiedTime:'',text:'',error:e.message});continue}const base={sourceId:stableId('source',m.id),fileId:m.id,title:m.name||item.root||m.id,mimeType:m.mimeType||'',url:m.webViewLink||sourceUrl(m.id,m.mimeType),parentSourceId:item.parentId?stableId('source',item.parentId):'',rootSource:item.root,status:'연결됨',modifiedTime:m.modifiedTime||'',text:'',error:''};if(m.mimeType===FOLDER){sources.push(base);try{for(const child of await listFolder(token,m.id))if(!seen.has(child.id)&&sources.length+queue.length<MAX_SOURCES)queue.push({id:child.id,root:item.root,parentId:m.id,depth:item.depth+1})}catch(e){base.status='연결 안 됨';base.error=e.message}continue}if(!READABLE.has(m.mimeType)){base.status='연결 안 됨';base.error='현재 자동 분석을 지원하지 않는 파일 형식';sources.push(base);continue}try{const r=await readSource(token,m);base.text=r.text||'';sources.push(base);for(const url of r.links||[]){const id=driveIdFromUrl(url);if(id&&!seen.has(id)&&sources.length+queue.length<MAX_SOURCES)queue.push({id,root:item.root,parentId:m.id,depth:item.depth+1})}}catch(e){base.status='연결 안 됨';base.error=e.message;sources.push(base)}}
  const required=roots.map(r=>{const s=sources.find(x=>x.fileId===r.id);return {id:r.id,title:r.root,status:s?.status||'연결 안 됨',url:s?.url||sourceUrl(r.id,'application/vnd.google-apps.document'),error:s?.error||''}});
  return {sources,required,limitReached:queue.length>0||sources.length>=MAX_SOURCES};
}
async function gemini(prompt,model=MODEL){if(!process.env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY 미설정');const order=[...new Set([model,'gemini-2.5-flash-lite','gemini-2.5-flash'])],errors=[];for(const m of order){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:.1}})});if(!r.ok){errors.push(`${m}: ${r.status} ${(await r.text()).slice(0,220)}`);continue}const d=await r.json(),txt=(d.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('');return {data:JSON.parse(cleanJSON(txt)),modelUsed:m}}catch(e){errors.push(`${m}: ${e.message||e}`)}}throw new Error(`Gemini 호출 실패: ${errors.join(' | ')}`)}
function corpusBatches(sources){const blocks=[];for(const s of sources.filter(x=>x.status==='연결됨'&&clean(x.text))){const text=String(s.text);for(let i=0;i<text.length;i+=60000)blocks.push(`\n<SOURCE id="${s.sourceId}" title="${s.title}" root="${s.rootSource}" url="${s.url}">\n${text.slice(i,i+60000)}\n</SOURCE>`)}const batches=[];let cur='',total=0;for(const b of blocks){if(total>=MAX_CORPUS_CHARS)break;const piece=b.slice(0,MAX_CORPUS_CHARS-total);if(cur&&cur.length+piece.length>180000){batches.push(cur);cur=''}cur+=piece;total+=piece.length}if(cur)batches.push(cur);return {batches,total,truncated:blocks.reduce((n,b)=>n+b.length,0)>total}}
function arr(v){return Array.isArray(v)?v:[]}
function normalizeCandidate(p,sourceIds=[]){return {name:safe(p.name,180),category:safe(p.category,80),status:safe(p.status,80),customer:safe(p.customer,220),summary:safe(p.summary,1200),evidence:safe(p.evidence,1200),sourceIds:[...new Set([...sourceIds,...arr(p.sourceIds).map(clean).filter(Boolean)])],features:arr(p.features).map(f=>({name:safe(f.name||f,180),description:safe(f.description,700),status:safe(f.status,80)})).filter(f=>f.name),devices:arr(p.devices).map(d=>({name:safe(d.name||d,180),role:safe(d.role,500),model:safe(d.model,180)})).filter(d=>d.name)}}
async function extractProjects(corpus){const packed=corpusBatches(corpus.sources);if(!packed.batches.length)return {projects:[],modelUsed:null,truncated:packed.truncated};const candidates=[];let modelUsed=null;for(const batch of packed.batches){const prompt=`TeamGRIT 내부 원본 자료에서 실제 프로젝트를 구조화한다. 제공된 SOURCE 텍스트만 사용한다. 샘플, 추정, 일반 지식, 문서에 없는 담당자/기한/상태/장비/기능을 만들지 마라. 프로젝트/PoC/납품/행사/제품 개편처럼 독립적으로 진행되는 실제 업무 단위가 자료에서 명시적으로 확인될 때만 project로 반환한다. 단순 기능명, 제품명, 연구 주제만으로 프로젝트를 새로 만들지 마라. category/status/customer가 명시되지 않으면 빈 문자열. features/devices도 해당 프로젝트와의 연결이 텍스트에서 확인될 때만 넣는다. evidence는 짧은 원문 근거 요약. sourceIds에는 근거 SOURCE id만 넣는다. JSON만 반환: {"projects":[{"name":string,"category":string,"status":string,"customer":string,"summary":string,"evidence":string,"sourceIds":[string],"features":[{"name":string,"description":string,"status":string}],"devices":[{"name":string,"role":string,"model":string}]}]}.\n${batch}`;const ai=await gemini(prompt);modelUsed=ai.modelUsed;for(const p of arr(ai.data?.projects)){const n=normalizeCandidate(p);if(n.name)candidates.push(n)}}if(!candidates.length)return {projects:[],modelUsed,truncated:packed.truncated};const mergePrompt=`다음은 같은 실제 TeamGRIT 원본 자료에서 추출한 프로젝트 후보다. 명백히 동일한 프로젝트만 병합하고 이름이 비슷하다는 이유만으로 합치지 마라. 새로운 사실을 추가하지 말고 입력에 없는 값을 추정하지 마라. sourceIds/features/devices/evidence를 보존·통합한다. 상태나 고객이 충돌하면 더 구체적인 값을 임의 선택하지 말고 입력에 반복적으로/명시적으로 나타난 값만 사용하며 불확실하면 빈 문자열. JSON만 반환: {"projects":[{"name":string,"category":string,"status":string,"customer":string,"summary":string,"evidence":string,"sourceIds":[string],"features":[{"name":string,"description":string,"status":string}],"devices":[{"name":string,"role":string,"model":string}]}]}.\nCANDIDATES:\n${JSON.stringify(candidates).slice(0,220000)}`;const merged=await gemini(mergePrompt);modelUsed=merged.modelUsed||modelUsed;const validIds=new Set(corpus.sources.map(s=>s.sourceId));const projects=arr(merged.data?.projects).map(p=>normalizeCandidate(p)).filter(p=>p.name).map(p=>({...p,sourceIds:p.sourceIds.filter(id=>validIds.has(id))}));return {projects,modelUsed,truncated:packed.truncated}}
function normalizedName(v=''){return clean(v).toLowerCase().replace(/^\[[^\]]+\]\s*/,'').replace(/[\s_\-–—·:()\[\]]+/g,'').replace(/프로젝트$/,'')}
function buildEntities(projects,existing=[]){const oldById=new Map(existing.map(p=>[p.project_id||p.id,p])),oldByName=new Map(existing.map(p=>[normalizedName(p.name),p]));const now=new Date().toISOString(),out=[],features=[],devices=[];for(const p of projects){const key=normalizedName(p.name),id=stableId('project',key||p.name),old=oldById.get(id)||oldByName.get(key)||{};const sourceIds=[...new Set(p.sourceIds||[])];out.push({project_id:id,name:p.name,source_category:p.category||'',source_status:p.status||'',customer:p.customer||'',summary:p.summary||'',drive_url:old.drive_url||old.driveUrl||'',figma_url:old.figma_url||old.figmaUrl||'',source_ids:sourceIds.join(','),source_evidence:p.evidence||'',last_synced_at:now,connection_status:'연결됨',manual_category:old.manual_category||'',manual_status:old.manual_status||'',manual_updated_at:old.manual_updated_at||''});for(const f of p.features||[]){const name=clean(f.name);if(!name)continue;features.push({feature_id:stableId('feature',`${id}:${normalizedName(name)}`),project_id:id,name,description:f.description||'',status:f.status||'',source_ids:sourceIds.join(','),last_synced_at:now})}for(const d of p.devices||[]){const name=clean(d.name);if(!name)continue;devices.push({device_id:stableId('device',`${id}:${normalizedName(name)}`),project_id:id,name,role:d.role||'',model:d.model||'',source_ids:sourceIds.join(','),last_synced_at:now})}}return {projects:out,features,devices}}
function sourceRows(corpus){const now=new Date().toISOString();return corpus.sources.map(s=>({source_id:s.sourceId,file_id:s.fileId,title:s.title,mime_type:s.mimeType,url:s.url,parent_source_id:s.parentSourceId,root_source:s.rootSource,status:s.status,modified_time:s.modifiedTime,last_synced_at:now,error:s.error||''}))}
function contextText(corpus,max=360000){let out='';for(const s of corpus.sources.filter(x=>x.status==='연결됨'&&clean(x.text))){const block=`\n<SOURCE id="${s.sourceId}" title="${s.title}" root="${s.rootSource}" url="${s.url}">\n${s.text}\n</SOURCE>`;if(out.length+block.length>max){out+=block.slice(0,Math.max(0,max-out.length));break}out+=block}return out}

module.exports={WORK_DOC_ID,SYSTEM_DEV_DOC_ID,MODEL,collectCorpus,extractProjects,buildEntities,sourceRows,contextText,gemini,stableId,clean,arr};
