const crypto=require('crypto');
function cookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function cookie(name,value,opts={}){const p=[`${name}=${encodeURIComponent(value)}`,'Path=/','HttpOnly','Secure','SameSite=Lax'];if(opts.maxAge!==undefined)p.push(`Max-Age=${opts.maxAge}`);return p.join('; ')}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
function redirect(res,url,set=[]){res.statusCode=302;if(set.length)res.setHeader('Set-Cookie',set);res.setHeader('Location',url);res.end()}
function origin(req){const proto=(req.headers['x-forwarded-proto']||'https').split(',')[0];return `${proto}://${req.headers.host}`}
async function body(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
async function refresh(rt){const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:rt,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:q});if(!r.ok)throw new Error('Google Chat token refresh failed');return r.json()}
async function token(req,res){const c=cookies(req);if(c.chat_access)return c.chat_access;if(!c.chat_refresh)return null;const t=await refresh(c.chat_refresh);res.setHeader('Set-Cookie',[cookie('chat_access',t.access_token,{maxAge:Math.max(300,(t.expires_in||3600)-120)}),cookie('chat_refresh',c.chat_refresh,{maxAge:60*60*24*30})]);return t.access_token}
async function gf(t,url){const r=await fetch(url,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)throw new Error(`Google Chat API ${r.status}: ${(await r.text()).slice(0,400)}`);return r.json()}
async function openaiJSON(prompt){if(!process.env.OPENAI_API_KEY)return null;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:prompt})});if(!r.ok)throw new Error(`OpenAI ${r.status}: ${(await r.text()).slice(0,250)}`);const d=await r.json();const text=(d.output||[]).flatMap(o=>o.content||[]).map(c=>c.text||'').join('').replace(/^```json\s*/,'').replace(/```$/,'').trim();return JSON.parse(text)}
module.exports=async(req,res)=>{try{const u=new URL(req.url,origin(req)),action=u.searchParams.get('action')||'status';
if(action==='auth'){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return redirect(res,'/?chat=not_configured');const state=crypto.randomBytes(18).toString('hex');const scope=['openid','email','profile','https://www.googleapis.com/auth/chat.spaces.readonly','https://www.googleapis.com/auth/chat.messages.readonly'].join(' ');const q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:`${origin(req)}/api/chat?action=callback`,response_type:'code',scope,access_type:'offline',prompt:'consent',include_granted_scopes:'true',state});return redirect(res,`https://accounts.google.com/o/oauth2/v2/auth?${q}`,[cookie('chat_state',state,{maxAge:600})])}
if(action==='callback'){const c=cookies(req),code=u.searchParams.get('code'),state=u.searchParams.get('state');if(!code||!state||state!==c.chat_state)return redirect(res,'/?chat=auth_error');const q=new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',redirect_uri:`${origin(req)}/api/chat?action=callback`,grant_type:'authorization_code'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:q});if(!r.ok)return redirect(res,'/?chat=token_error');const t=await r.json();return redirect(res,'/?chat=connected',[cookie('chat_access',t.access_token,{maxAge:Math.max(300,(t.expires_in||3600)-120)}),cookie('chat_refresh',t.refresh_token||'',{maxAge:60*60*24*30}),cookie('chat_state','',{maxAge:0})])}
if(action==='logout'){res.setHeader('Set-Cookie',[cookie('chat_access','',{maxAge:0}),cookie('chat_refresh','',{maxAge:0})]);return json(res,200,{ok:true})}
const t=await token(req,res);if(action==='status')return json(res,200,{connected:!!t,configured:!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET)});if(!t)return json(res,401,{error:'google_chat_not_connected'});
if(action==='spaces'){const d=await gf(t,'https://chat.googleapis.com/v1/spaces?pageSize=100');return json(res,200,{spaces:(d.spaces||[]).map(s=>({name:s.name,displayName:s.displayName||s.spaceDetails?.description||s.name,type:s.spaceType||s.type||''}))})}
if(action==='messages'){const space=u.searchParams.get('space')||'';if(!/^spaces\//.test(space))return json(res,400,{error:'space_required'});const pageSize=Math.min(100,Math.max(1,Number(u.searchParams.get('pageSize')||50)));const d=await gf(t,`https://chat.googleapis.com/v1/${space}/messages?pageSize=${pageSize}&orderBy=createTime%20desc`);return json(res,200,{messages:(d.messages||[]).map(m=>({name:m.name,text:m.text||m.formattedText||'',createTime:m.createTime||'',sender:m.sender?.displayName||m.sender?.name||'',thread:m.thread?.name||'',space:m.space?.name||space}))})}
if(action==='analyze'){if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const b=await body(req),messages=Array.isArray(b.messages)?b.messages.slice(0,100):[];const transcript=messages.map(m=>`[${m.createTime||''}] ${m.sender||''}: ${m.text||''}`).join('\n').slice(0,60000);const prompt=`You are TeamGRIT's internal operations analyst. Analyze Google Chat messages for the given project. Ignore casual chat. Extract only operationally meaningful new information. Return ONLY valid JSON with keys: summary (string), facts (array of {type,detail,confidence}), tasks (array of {title,reason,priority}), needsDriveConfirmation (array of strings). Types: 일정,결정,요청,담당자,장비,기능,이슈,완료,외부대기. priority: 높음,보통,낮음. Chat is NOT the source of truth: anything that should update an official project record must be put in needsDriveConfirmation instead of being treated as final.\nPROJECT: ${b.projectName||''}\nMESSAGES:\n${transcript}`;let analysis=await openaiJSON(prompt);if(!analysis)analysis={summary:`Google Chat 메시지 ${messages.length}건을 확인했습니다. OPENAI_API_KEY가 설정되면 결정·일정·요청·업무를 자동 분류합니다.`,facts:[],tasks:[],needsDriveConfirmation:[]};return json(res,200,{analysis})}
return json(res,400,{error:'unsupported_action'});}catch(e){return json(res,500,{error:e.message})}};