require('./_lib/gemini-model-compat')();
const original=require('./data-all');
const central=require('./_lib/central-entities');

function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
async function refresh(rt){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:rt,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;return (await refresh(c.g_refresh)).access_token}
function fakeResponse(){const headers={};return {statusCode:200,body:'',headers,setHeader(k,v){headers[k]=v},end(v){this.body=v==null?'':String(v)}}}
function uniqueById(rows,key){const m=new Map();for(const r of rows){if(r&&r[key])m.set(r[key],r)}return [...m.values()]}
async function syncProductFacts(token,projects=[]){const now=new Date().toISOString(),facts=[];for(const p of projects||[]){const ids=Array.isArray(p.sourceIds)?p.sourceIds:[],joined=ids.join(','),evidence=p.sourceEvidence||'';if(p.summary)facts.push({fact_id:central.id('fact',`${p.id}|summary`),project_id:p.id,subject:'프로젝트 요약',fact:p.summary,source_ids:joined,evidence,verification_status:ids.length?'원본 확인':'근거 확인 필요',last_synced_at:now});for(const f of p.features||[])if(f.name)facts.push({fact_id:central.id('fact',`${p.id}|feature|${f.name}`),project_id:p.id,subject:`기능 · ${f.name}`,fact:f.description||f.name,source_ids:joined,evidence,verification_status:ids.length?'원본 확인':'근거 확인 필요',last_synced_at:now});for(const d of p.devices||[])if(d.name)facts.push({fact_id:central.id('fact',`${p.id}|device|${d.name}`),project_id:p.id,subject:`장비 · ${d.name}`,fact:[d.role,d.model].filter(Boolean).join(' · ')||d.name,source_ids:joined,evidence,verification_status:ids.length?'원본 확인':'근거 확인 필요',last_synced_at:now})}await central.replace(token,'ProductFacts',uniqueById(facts,'fact_id'));return facts.length}
async function attachEntities(token,payload){await central.ensure(token);const [approvals,customers,productFacts,results]=await Promise.all(['Approvals','Customers','ProductFacts','Results'].map(n=>central.list(token,n)));payload.entities={approvals,customers,productFacts,results};if(payload.data)payload.data.entities=payload.entities;return payload}

module.exports=async(req,res)=>{const temp=fakeResponse();try{await original(req,temp);let payload={};try{payload=JSON.parse(temp.body||'{}')}catch{payload={raw:temp.body}}const token=await access(req).catch(()=>null);if(token&&temp.statusCode<400){const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action')||'bootstrap',projects=payload.data?.projects||payload.projects||[];if((action==='sync'||action==='bootstrap'||action==='project')&&Array.isArray(projects)&&projects.length)payload.productFactsSynced=await syncProductFacts(token,projects);await attachEntities(token,payload)}res.statusCode=temp.statusCode;for(const [k,v] of Object.entries(temp.headers))res.setHeader(k,v);res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(payload))}catch(e){res.statusCode=500;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify({error:e.message,connection:'연결 안 됨'}))}};
