const crypto=require('crypto');
const OPS_SHEET_ID=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';

function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
async function refresh(refreshToken){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:refreshToken,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;return (await refresh(c.g_refresh)).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);if(r.status===204)return null;const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
function uid(){return `project_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`}
function clean(v){return v===undefined||v===null?'':String(v).trim()}
function driveFolderId(url=''){const m=String(url).match(/\/folders\/([A-Za-z0-9_-]+)/);return m?m[1]:''}
async function getValues(token,range){return gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(range)}`)}
async function putValues(token,range,values){return gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(range)}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})})}
async function appendValues(token,range,values){return gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(range)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})})}
async function projects(token){const d=await getValues(token,'Projects!A1:G1000');const rows=d.values||[];const header=rows[0]||[];return rows.slice(1).filter(r=>clean(r[0])).map(r=>{const o={};header.forEach((h,i)=>o[h]=r[i]??'');return {id:o.project_id,name:o.name,category:o.category||'기타',status:o.status||'확인 필요',driveUrl:o.drive_url||'',driveFolderId:driveFolderId(o.drive_url||''),figmaUrl:o.figma_url||'',updatedAt:o.updated_at||'',relatedTechnologyIds:[],relatedCompanyIds:[],requests:[],results:[]}})}
async function executions(token){const d=await getValues(token,'Executions!A1:Z1000').catch(()=>({values:[]}));const rows=d.values||[];if(rows.length<2)return [];const header=rows[0]||[];return rows.slice(1).filter(r=>r.some(v=>clean(v))).map(r=>{const o={};header.forEach((h,i)=>o[h]=r[i]??'');return o})}
async function findProjectRow(token,id){const d=await getValues(token,'Projects!A1:G1000');const rows=d.values||[];for(let i=1;i<rows.length;i++)if(clean(rows[i][0])===id)return {row:i+1,values:rows[i]};return null}
async function saveProject(token,b){const id=clean(b.id)||uid(),now=new Date().toISOString(),row=[id,clean(b.name),clean(b.category)||'기타',clean(b.status)||'예정',clean(b.driveUrl),clean(b.figmaUrl),now];if(!row[1])throw new Error('project_name_required');const found=await findProjectRow(token,id);if(found)await putValues(token,`Projects!A${found.row}:G${found.row}`,[row]);else await appendValues(token,'Projects!A:G',[row]);return {id,name:row[1],category:row[2],status:row[3],driveUrl:row[4],driveFolderId:driveFolderId(row[4]),figmaUrl:row[5],updatedAt:now,relatedTechnologyIds:[],relatedCompanyIds:[],requests:[],results:[]}}
async function logExecution(token,b){const now=new Date().toISOString();const d=await getValues(token,'Executions!A1:Z5').catch(()=>({values:[]}));let header=(d.values||[])[0]||[];const wanted=['execution_id','project_id','action','model','status','error','started_at','finished_at','source'];if(!header.length){header=wanted;await putValues(token,'Executions!A1:I1',[header])}const valueMap={execution_id:clean(b.executionId)||`exec_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`,project_id:clean(b.projectId),action:clean(b.action),model:clean(b.model),status:clean(b.status)||'완료',error:clean(b.error),started_at:clean(b.startedAt)||now,finished_at:clean(b.finishedAt)||now,source:clean(b.source)||'TeamGRIT Ops'};const row=header.map(h=>valueMap[h]??'');await appendValues(token,`Executions!A:${String.fromCharCode(64+Math.min(header.length,26))}`,[row]);return valueMap}

module.exports=async(req,res)=>{try{const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action')||'bootstrap';if(req.method==='GET'&&action==='bootstrap')return json(res,200,{source:'TeamGRIT Ops 운영 데이터',spreadsheetId:OPS_SHEET_ID,projects:await projects(token),executions:await executions(token)});if(req.method==='POST'&&action==='project'){const b=await readBody(req);return json(res,200,{ok:true,project:await saveProject(token,b)});if(req.method==='POST'&&action==='execution'){const b=await readBody(req);return json(res,200,{ok:true,execution:await logExecution(token,b)});return json(res,404,{error:'not_found'});}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}}
