const crypto=require('crypto');
const OPS=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';
const HEAD={
  Projects:['project_id','name','source_category','source_status','customer','summary','drive_url','figma_url','source_ids','source_evidence','last_synced_at','connection_status','manual_category','manual_status','manual_updated_at'],
  Features:['feature_id','project_id','name','description','status','source_ids','last_synced_at'],
  Devices:['device_id','project_id','name','role','model','source_ids','last_synced_at'],
  Sources:['source_id','file_id','title','mime_type','url','parent_source_id','root_source','status','read_status','read_detail','content_chars','discovered_links','modified_time','last_synced_at','error'],
  Executions:['run_id','project_id','project_name','action','output_type','model','status','started_at','finished_at','file_url','error'],
  _State:['key','value','status','updated_at','error'],
  Approvals:['approval_id','target_type','target_id','action','status','requested_at','approved_by','approved_at','source','note'],
  Customers:['customer_id','company_id','company_name','partner','end_customer','customer_type','industry','sales_temperature','account_owner','contact_id','contact_name','contact_email','contact_phone','source','last_synced_at'],
  ProductFacts:['fact_id','project_id','subject','fact','source_ids','evidence','verification_status','last_synced_at'],
  Results:['result_id','project_id','task_id','execution_id','type','title','file_url','status','created_at']
};
const clean=v=>v==null?'':String(v).trim();
function cookies(req){const o={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return o}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
async function access(req){const c=cookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:c.g_refresh,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('Google token refresh failed');return (await r.json()).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);return r.status===204?null:((r.headers.get('content-type')||'').includes('json')?r.json():r.text())}
function objects(values,headers){const rows=values||[],h=rows[0]||headers;return rows.slice(1).filter(r=>r.some(v=>clean(v))).map(r=>{const o={};h.forEach((k,i)=>o[k]=r[i]??'');return o})}
function effective(o,f,d,s){const ids=clean(o.source_ids).split(',').filter(Boolean);return {id:o.project_id,name:o.name,category:o.manual_category||o.source_category||'기타',status:o.manual_status||o.source_status||'확인 필요',sourceCategory:o.source_category||'',sourceStatus:o.source_status||'',customer:o.customer||'',summary:o.summary||'',driveUrl:o.drive_url||'',driveFolderId:(String(o.drive_url||'').match(/\/folders\/([A-Za-z0-9_-]+)/)||[])[1]||'',figmaUrl:o.figma_url||'',sourceIds:ids,sourceEvidence:o.source_evidence||'',updatedAt:o.manual_updated_at||o.last_synced_at||'',connectionStatus:o.connection_status||'연결 안 됨',features:f.filter(x=>x.project_id===o.project_id),devices:d.filter(x=>x.project_id===o.project_id),sources:s.filter(x=>ids.includes(x.source_id))}}
async function batch(token){const names=Object.keys(HEAD),params=names.map(n=>`ranges=${encodeURIComponent(n+'!A1:Z5000')}`).join('&'),d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values:batchGet?${params}`),out={};(d.valueRanges||[]).forEach((v,i)=>out[names[i]]=objects(v.values,HEAD[names[i]]));for(const n of names)out[n]=out[n]||[];return out}
async function bootstrap(token){const x=await batch(token),state={};for(const r of x._State)if(r.key)state[r.key]=r;const sync=state.project_sync||null,last=Date.parse(sync?.updated_at||0)||0;return {source:'TeamGRIT Ops 운영 데이터',spreadsheetId:OPS,projects:x.Projects.map(p=>effective(p,x.Features,x.Devices,x.Sources)),features:x.Features,devices:x.Devices,sources:x.Sources,executions:x.Executions,approvals:x.Approvals,customers:x.Customers,productFacts:x.ProductFacts,results:x.Results,syncState:sync,needsSync:!sync||!['성공','부분 성공'].includes(sync.status)||!last||Date.now()-last>30*60*1000}}
async function updateProject(token,b){const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent('Projects!A1:O5000')}`),rows=d.values||[],h=rows[0]||HEAD.Projects,idx=rows.findIndex((r,i)=>i>0&&clean(r[0])===clean(b.id));if(idx<1)throw new Error('source_project_not_found');const row=[...rows[idx]];while(row.length<h.length)row.push('');const now=new Date().toISOString();const set=(key,val)=>{const i=h.indexOf(key);if(i>=0)row[i]=val};if(Object.prototype.hasOwnProperty.call(b,'driveUrl'))set('drive_url',clean(b.driveUrl));if(Object.prototype.hasOwnProperty.call(b,'figmaUrl'))set('figma_url',clean(b.figmaUrl));if(Object.prototype.hasOwnProperty.call(b,'category'))set('manual_category',clean(b.category));if(Object.prototype.hasOwnProperty.call(b,'status'))set('manual_status',clean(b.status));set('manual_updated_at',now);await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent('Projects!A'+(idx+1)+':O'+(idx+1))}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[row]})});const all=await bootstrap(token);return all.projects.find(p=>p.id===clean(b.id))}
async function logExecution(token,b){const now=new Date().toISOString(),row=[clean(b.run_id)||`run_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`,clean(b.project_id),clean(b.project_name),clean(b.action),clean(b.output_type),clean(b.model),clean(b.status)||'완료',clean(b.started_at)||now,clean(b.finished_at)||now,clean(b.file_url),clean(b.error)];await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent('Executions!A:K')}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[row]})});return row}
module.exports=async(req,res)=>{try{const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action')||'bootstrap';if(req.method==='GET'&&action==='bootstrap')return json(res,200,await bootstrap(token));if(req.method==='POST'&&action==='project')return json(res,200,{ok:true,project:await updateProject(token,await body(req))});if(req.method==='POST'&&action==='execution')return json(res,200,{ok:true,execution:await logExecution(token,await body(req))});if(req.method==='POST'&&action==='sync')return json(res,409,{error:'incremental_sync_required'});return json(res,404,{error:'not_found'})}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}};
