require('./_lib/gemini-model-compat')();
const crypto=require('crypto');
const {collectCorpus,extractProjects,buildEntities,sourceRows,clean}=require('./_lib/source-corpus-all');
const OPS_SHEET_ID=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';
const SCHEMA={
  _State:['key','value','status','updated_at','error'],
  Projects:['project_id','name','source_category','source_status','customer','summary','drive_url','figma_url','source_ids','source_evidence','last_synced_at','connection_status','manual_category','manual_status','manual_updated_at'],
  Features:['feature_id','project_id','name','description','status','source_ids','last_synced_at'],
  Devices:['device_id','project_id','name','role','model','source_ids','last_synced_at'],
  Sources:['source_id','file_id','title','mime_type','url','parent_source_id','root_source','status','read_status','read_detail','content_chars','discovered_links','modified_time','last_synced_at','error'],
  Tasks:['task_id','title','project','owner','due_date','status','source','source_url','source_ids','created_at','approved_at','updated_at'],
  Executions:['run_id','project_id','project_name','action','output_type','model','status','started_at','finished_at','file_url','error']
};
function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
async function refresh(refreshToken){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:refreshToken,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;return (await refresh(c.g_refresh)).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);if(r.status===204)return null;return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
async function getValues(token,range){return gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(range)}`)}
async function putValues(token,range,values){return gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(range)}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})})}
async function appendValues(token,range,values){return gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(range)}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})})}
async function clearValues(token,range){return gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(range)}:clear`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})}
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
async function ensureSchema(token){const meta=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}?fields=sheets.properties`),have=new Set((meta.sheets||[]).map(s=>s.properties?.title)),requests=[];for(const name of Object.keys(SCHEMA))if(!have.has(name))requests.push({addSheet:{properties:{title:name,hidden:name==='_State'}}});if(requests.length)await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}:batchUpdate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests})});for(const [name,headers] of Object.entries(SCHEMA)){const current=((await getValues(token,`${name}!A1:Z1`).catch(()=>({values:[]}))).values||[])[0]||[];if(headers.some((h,i)=>current[i]!==h)||current.length!==headers.length)await putValues(token,`${name}!A1:${col(headers.length)}1`,[headers])}}
function rowsToObjects(values,headers){const rows=values||[],head=rows[0]||headers;return rows.slice(1).filter(r=>r.some(v=>clean(v))).map(r=>{const o={};head.forEach((h,i)=>o[h]=r[i]??'');return o})}
async function table(token,name){const d=await getValues(token,`${name}!A1:Z5000`).catch(()=>({values:[]}));return rowsToObjects(d.values,SCHEMA[name])}
async function writeTable(token,name,objects){const headers=SCHEMA[name],last=col(headers.length);await clearValues(token,`${name}!A2:${last}5000`).catch(()=>{});await putValues(token,`${name}!A1:${last}1`,[headers]);if(objects.length)await putValues(token,`${name}!A2:${last}${objects.length+1}`,objects.map(o=>headers.map(h=>o[h]??'')))}
async function readState(token){const rows=await table(token,'_State'),out={};for(const r of rows)if(r.key)out[r.key]=r;return out}
async function setState(token,key,{value='',status='',error=''}={}){const state=await readState(token),now=new Date().toISOString();state[key]={key,value:String(value??''),status:String(status??''),updated_at:now,error:String(error??'')};await writeTable(token,'_State',Object.values(state));return state[key]}
function effectiveProject(o,features=[],devices=[],sources=[]){const ids=clean(o.source_ids).split(',').filter(Boolean);return {id:o.project_id,name:o.name,category:o.manual_category||o.source_category||'기타',status:o.manual_status||o.source_status||'확인 필요',sourceCategory:o.source_category||'',sourceStatus:o.source_status||'',customer:o.customer||'',summary:o.summary||'',driveUrl:o.drive_url||'',driveFolderId:(String(o.drive_url||'').match(/\/folders\/([A-Za-z0-9_-]+)/)||[])[1]||'',figmaUrl:o.figma_url||'',sourceIds:ids,sourceEvidence:o.source_evidence||'',updatedAt:o.manual_updated_at||o.last_synced_at||'',connectionStatus:o.connection_status||'연결 안 됨',features:features.filter(f=>f.project_id===o.project_id),devices:devices.filter(d=>d.project_id===o.project_id),sources:sources.filter(s=>ids.includes(s.source_id))}}
async function bootstrapData(token){await ensureSchema(token);const [p,f,d,s,e,state]=await Promise.all([table(token,'Projects'),table(token,'Features'),table(token,'Devices'),table(token,'Sources'),table(token,'Executions'),readState(token)]);const sync=state.project_sync||null,last=sync?.updated_at?Date.parse(sync.updated_at):0,needsSync=!sync||!['성공','부분 성공'].includes(sync.status)||!last||Date.now()-last>10*60*1000;return {source:'TeamGRIT Ops 운영 데이터',spreadsheetId:OPS_SHEET_ID,projects:p.map(x=>effectiveProject(x,f,d,s)),features:f,devices:d,sources:s,executions:e,syncState:sync,needsSync}}
function runId(){return `run_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`}
async function logExecution(token,b){const now=new Date().toISOString(),row={run_id:clean(b.run_id)||runId(),project_id:clean(b.project_id),project_name:clean(b.project_name),action:clean(b.action),output_type:clean(b.output_type),model:clean(b.model),status:clean(b.status)||'완료',started_at:clean(b.started_at)||now,finished_at:clean(b.finished_at)||now,file_url:clean(b.file_url),error:clean(b.error)};await appendValues(token,'Executions!A:K',[SCHEMA.Executions.map(h=>row[h]??'')]);return row}
async function syncSources(token){const started=new Date().toISOString();await setState(token,'schema',{value:'teamgrit-ops-central-v3',status:'정상'});await setState(token,'project_sync',{value:'최신 원본 전체 수집 중',status:'진행 중'});try{const corpus=await collectCorpus(token);await writeTable(token,'Sources',sourceRows(corpus));const missing=corpus.required.filter(r=>r.status!=='연결됨');if(missing.length){const msg=missing.map(r=>`${r.title}: 연결 안 됨`).join(', ');await setState(token,'project_sync',{value:'필수 원본 연결 실패',status:'실패',error:msg});return {ok:false,error:msg,requiredSources:corpus.required}}
const existing=await table(token,'Projects'),extracted=await extractProjects(corpus);if(!extracted.projects.length)throw new Error('최신 원본에서 근거가 확인된 프로젝트를 추출하지 못했습니다. 기존 중앙 데이터는 유지했습니다.');const built=buildEntities(extracted.projects,existing);await Promise.all([writeTable(token,'Projects',built.projects),writeTable(token,'Features',built.features),writeTable(token,'Devices',built.devices)]);const unreadable=corpus.sources.filter(s=>s.readStatus==='연결 안 됨').length,partial=corpus.sources.filter(s=>s.readStatus==='일부 읽음').length,warning=unreadable||partial?`전체 읽음 ${corpus.sources.length-unreadable-partial}개 · 일부 읽음 ${partial}개 · 연결 안 됨 ${unreadable}개`:'';await setState(token,'project_sync',{value:`프로젝트 ${built.projects.length}건 · 원본 ${corpus.sources.length}건`,status:warning?'부분 성공':'성공',error:warning});await setState(token,'project_sync_model',{value:extracted.modelUsed||'',status:extracted.modelUsed?'정상':'연결 안 됨'});await logExecution(token,{action:'프로젝트 최신 원본 전체 동기화',model:extracted.modelUsed||'',status:warning?'부분 성공':'성공',started_at:started,error:warning});return {ok:true,projects:built.projects.length,features:built.features.length,devices:built.devices.length,sources:corpus.sources.length,fullRead:corpus.sources.length-unreadable-partial,partialRead:partial,unreadable,modelUsed:extracted.modelUsed,requiredSources:corpus.required,warning,data:await bootstrapData(token)}}catch(e){await setState(token,'project_sync',{value:'동기화 실패',status:'실패',error:e.message}).catch(()=>{});await logExecution(token,{action:'프로젝트 최신 원본 전체 동기화',status:'실패',started_at:started,error:e.message}).catch(()=>{});throw e}}
async function updateProject(token,b){const rows=await table(token,'Projects'),idx=rows.findIndex(r=>r.project_id===clean(b.id));if(idx<0)throw new Error('source_project_not_found');const p=rows[idx],now=new Date().toISOString();if(Object.prototype.hasOwnProperty.call(b,'driveUrl'))p.drive_url=clean(b.driveUrl);if(Object.prototype.hasOwnProperty.call(b,'figmaUrl'))p.figma_url=clean(b.figmaUrl);if(Object.prototype.hasOwnProperty.call(b,'category'))p.manual_category=clean(b.category);if(Object.prototype.hasOwnProperty.call(b,'status'))p.manual_status=clean(b.status);p.manual_updated_at=now;rows[idx]=p;await writeTable(token,'Projects',rows);const [f,d,s]=await Promise.all([table(token,'Features'),table(token,'Devices'),table(token,'Sources')]);return effectiveProject(p,f,d,s)}
module.exports=async(req,res)=>{try{const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action')||'bootstrap';if(req.method==='GET'&&action==='bootstrap')return json(res,200,await bootstrapData(token));if(req.method==='POST'&&action==='sync')return json(res,200,await syncSources(token));if(req.method==='POST'&&action==='project'){await ensureSchema(token);return json(res,200,{ok:true,project:await updateProject(token,await readBody(req))})}if(req.method==='POST'&&action==='execution'){await ensureSchema(token);return json(res,200,{ok:true,execution:await logExecution(token,await readBody(req))})}return json(res,404,{error:'not_found'})}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}};
