const crypto=require('crypto');
function parseCookies(req){const raw=req.headers.cookie||'',out={};raw.split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
async function refresh(refreshToken){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:refreshToken,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;return (await refresh(c.g_refresh)).access_token}
async function gf(token,url){const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,300)}`);return r.json()}
function folderId(v=''){const m=String(v).match(/\/folders\/([A-Za-z0-9_-]+)/);return m?m[1]:String(v).trim()}
function docText(doc){const out=[];for(const block of doc.body?.content||[]){for(const el of block.paragraph?.elements||[])if(el.textRun?.content)out.push(el.textRun.content);for(const row of block.table?.tableRows||[])for(const cell of row.tableCells||[])for(const c of cell.content||[])for(const el of c.paragraph?.elements||[])if(el.textRun?.content)out.push(el.textRun.content)}return out.join('').trim()}
function sheetText(ss){const lines=[];for(const sh of ss.sheets||[]){lines.push(`# ${sh.properties?.title||'Sheet'}`);for(const row of (sh.data?.[0]?.rowData||[]).slice(0,160)){const vals=(row.values||[]).slice(0,24).map(v=>v.formattedValue??v.effectiveValue?.stringValue??v.effectiveValue?.numberValue??'');if(vals.some(v=>String(v).trim()))lines.push(vals.join(' | '))}}return lines.join('\n').slice(0,45000)}
function slideText(p){const out=[];for(const [i,s] of (p.slides||[]).entries()){out.push(`# Slide ${i+1}`);for(const pe of s.pageElements||[]){const txt=(pe.shape?.text?.textElements||[]).map(x=>x.textRun?.content||'').join('').trim();if(txt)out.push(txt)}}return out.join('\n').slice(0,40000)}
function formText(f){const out=[f.info?.title||'Form'];for(const [i,it] of (f.items||[]).entries())out.push(`${i+1}. ${it.title||''}`);return out.join('\n').slice(0,25000)}
async function readFile(token,file){if(file.mimeType==='application/vnd.google-apps.document')return docText(await gf(token,`https://docs.googleapis.com/v1/documents/${file.id}`));if(file.mimeType==='application/vnd.google-apps.spreadsheet')return sheetText(await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${file.id}?includeGridData=true`));if(file.mimeType==='application/vnd.google-apps.presentation')return slideText(await gf(token,`https://slides.googleapis.com/v1/presentations/${file.id}`));if(file.mimeType==='application/vnd.google-apps.form')return formText(await gf(token,`https://forms.googleapis.com/v1/forms/${file.id}`));return ''}
function hash(text=''){return crypto.createHash('sha256').update(String(text)).digest('hex')}
async function openaiJSON(prompt){if(!process.env.OPENAI_API_KEY)return null;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:prompt})});if(!r.ok)throw new Error(`OpenAI ${r.status}: ${(await r.text()).slice(0,250)}`);const d=await r.json();const text=(d.output||[]).flatMap(o=>o.content||[]).map(c=>c.text||'').join('').replace(/^```json\s*/,'').replace(/```$/,'').trim();return JSON.parse(text)}
module.exports=async(req,res)=>{try{if(req.method!=='POST')return json(res,405,{error:'method_not_allowed'});const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req);if(b.mode==='snapshot'){const fid=folderId(b.folderId||'');if(!fid)return json(res,400,{error:'folder_required'});const q=encodeURIComponent(`'${fid}' in parents and trashed=false`);const d=await gf(token,`https://www.googleapis.com/drive/v3/files?q=${q}&pageSize=100&fields=files(id,name,mimeType,modifiedTime,webViewLink,size)`);const supported=new Set(['application/vnd.google-apps.document','application/vnd.google-apps.spreadsheet','application/vnd.google-apps.presentation','application/vnd.google-apps.form']);const files=[];for(const f of d.files||[]){let text='';if(supported.has(f.mimeType)){try{text=(await readFile(token,f)).slice(0,30000)}catch(e){text=`[읽기 실패: ${e.message}]`}}files.push({...f,contentHash:text?hash(text):'',contentText:text})}return json(res,200,{folderId:fid,files})}
if(b.mode==='analyze'){const before=String(b.beforeText||'').slice(0,30000),after=String(b.afterText||'').slice(0,30000),file=b.file||{};const prompt=`You are TeamGRIT's internal operations change analyst. Compare the previous and current content of one Google Drive file. Focus only on meaningful business/project changes, not formatting. Return ONLY valid JSON with keys: summary (string), changes (array of {type,detail,impact}), tasks (array of {title,reason,priority}). type examples: 요구사항,일정,결정,담당자,장비,기능,삭제. priority must be 높음,보통,낮음. If nothing meaningful changed, changes and tasks should be empty.\nPROJECT: ${b.projectName||''}\nFILE: ${file.name||''}\nPREVIOUS:\n${before}\nCURRENT:\n${after}`;let analysis=await openaiJSON(prompt);if(!analysis)analysis={summary:'파일 내용이 이전 Snapshot과 달라졌습니다. OPENAI_API_KEY가 설정되면 변경 의미와 후속 업무까지 분석합니다.',changes:[{type:'문서 변경',detail:'내용 해시가 변경됨',impact:'수동 검토 필요'}],tasks:[{title:`${file.name||'Drive 문서'} 변경 내용 검토`,reason:'이전 Snapshot과 현재 내용이 다름',priority:'보통'}]};return json(res,200,{analysis})}
return json(res,400,{error:'unsupported_mode'});}catch(e){return json(res,500,{error:e.message})}};