require('./_lib/gemini-model-compat')();
const original=require('./gemini');
const central=require('./_lib/central-entities');

function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
async function refresh(rt){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:rt,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;return (await refresh(c.g_refresh)).access_token}
function fakeResponse(){const headers={};return {statusCode:200,body:'',headers,setHeader(k,v){headers[k]=v},end(v){this.body=v==null?'':String(v)}}}
async function readRaw(req){let s='';for await(const c of req)s+=c;return s}
function cloneReq(req,raw){const clone=Object.create(req);clone.headers=req.headers;clone.url=req.url;clone.method=req.method;clone[Symbol.asyncIterator]=async function*(){if(raw)yield Buffer.from(raw)};return clone}
module.exports=async(req,res)=>{let raw='';try{raw=await readRaw(req)}catch{}let body={};try{body=JSON.parse(raw||'{}')}catch{}const temp=fakeResponse();try{await original(cloneReq(req,raw),temp);let payload={};try{payload=JSON.parse(temp.body||'{}')}catch{payload={raw:temp.body}}const token=await access(req).catch(()=>null),action=body.action||new URL(req.url,'https://x').searchParams.get('action')||'analyze';if(token&&temp.statusCode<400&&action==='execute'&&body.approved&&payload.ok){const approvedBy=await central.userEmail(token),taskId=body.task?.id||body.task?.task_id||'',projectId=body.project?.id||'',approval=central.approval({targetType:'Execution',targetId:taskId||payload.file?.id||Date.now(),action:'결과물 실행 승인',approvedBy,source:'프로젝트 업무 실행',note:body.task?.title||payload.generated?.title||''}),result=central.result({projectId,taskId,type:body.task?.outputType||payload.generated?.type||'',title:payload.file?.name||payload.generated?.title||body.task?.title||'실행 결과물',fileUrl:payload.file?.url||payload.file?.webViewLink||'',status:'완료'});await Promise.all([central.append(token,'Approvals',[approval]),central.append(token,'Results',[result])]);payload.approval=approval;payload.result=result}res.statusCode=temp.statusCode;for(const [k,v] of Object.entries(temp.headers))res.setHeader(k,v);res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(payload))}catch(e){res.statusCode=500;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify({error:e.message,connection:'연결 안 됨'}))}};
