const crypto=require('crypto');

function parseCookies(req){const raw=req.headers.cookie||'',out={};raw.split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function cookie(name,value,opts={}){const p=[`${name}=${encodeURIComponent(value)}`,`Path=/`];if(opts.httpOnly!==false)p.push('HttpOnly');if(opts.secure!==false)p.push('Secure');p.push(`SameSite=${opts.sameSite||'Lax'}`);if(opts.maxAge!==undefined)p.push(`Max-Age=${opts.maxAge}`);return p.join('; ')}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))}
function redirect(res,url,cookies=[]){res.statusCode=302;if(cookies.length)res.setHeader('Set-Cookie',cookies);res.setHeader('Location',url);res.end()}
function origin(req){const proto=(req.headers['x-forwarded-proto']||'https').split(',')[0];return `${proto}://${req.headers.host}`}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
function accountKey(email){return crypto.createHash('sha256').update(String(email).toLowerCase()).digest('hex').slice(0,16)}
function parseRegistry(c){try{return JSON.parse(Buffer.from(c.tg_gmail_accounts||'','base64url').toString('utf8'))||[]}catch{return []}}
function registryCookie(items){return cookie('tg_gmail_accounts',Buffer.from(JSON.stringify(items)).toString('base64url'),{maxAge:60*60*24*180})}
async function refresh(refreshToken){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:refreshToken,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Gmail token refresh failed');return r.json()}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok){const txt=await r.text();let parsed={};try{parsed=JSON.parse(txt)}catch{}const msg=parsed?.error?.message||txt;if(r.status===403&&/Gmail API has not been used|gmail\.googleapis\.com.*disabled|accessNotConfigured/i.test(msg))throw new Error('Gmail API가 Google Cloud 프로젝트에서 비활성화되어 있습니다. Google Cloud Console > APIs & Services > Library에서 Gmail API를 사용 설정한 뒤 2~5분 후 다시 시도해 주세요.');if(r.status===403&&/insufficient|scope|permission/i.test(msg))throw new Error('Gmail 권한이 부족합니다. Gmail 계정을 연결 해제한 뒤 다시 연결하여 메일 읽기/초안 작성 권한을 승인해 주세요.');throw new Error(`Google API ${r.status}: ${msg.slice(0,500)}`)}if(r.status===204)return null;const ct=r.headers.get('content-type')||'';return ct.includes('json')?r.json():r.text()}
async function accountAccess(req,res,key){const c=parseCookies(req);if(c[`gm_${key}_access`])return c[`gm_${key}_access`];const rt=c[`gm_${key}_refresh`];if(!rt)return null;const t=await refresh(rt);const existing=res.getHeader('Set-Cookie');const arr=Array.isArray(existing)?existing:existing?[existing]:[];arr.push(cookie(`gm_${key}_access`,t.access_token,{maxAge:Math.max(300,(t.expires_in||3600)-120)}));res.setHeader('Set-Cookie',arr);return t.access_token}
function headersMap(payload){const h={};for(const x of payload?.headers||[])h[String(x.name||'').toLowerCase()]=x.value||'';return h}
function decodePart(part){if(!part)return '';if(part.body?.data){try{return Buffer.from(part.body.data.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8')}catch{return ''}}for(const p of part.parts||[]){if((p.mimeType||'').startsWith('text/plain')){const t=decodePart(p);if(t)return t}}for(const p of part.parts||[]){const t=decodePart(p);if(t)return t}return ''}
function emailFrom(v=''){const m=String(v).match(/<([^>]+)>/);return (m?m[1]:v).trim()}
function gmailUrl(accountEmail,id,threadId){const account=encodeURIComponent(accountEmail||'0');return `https://mail.google.com/mail/u/${account}/#all/${threadId||id}`}
async function listMessages(token,q,maxResults=30,accountEmail=''){const qs=new URLSearchParams({q:q||'newer_than:90d',maxResults:String(Math.min(100,maxResults||30))});const l=await gf(token,`https://gmail.googleapis.com/gmail/v1/users/me/messages?${qs}`);const out=[];for(const m of (l.messages||[]).slice(0,Math.min(50,maxResults||30))){const x=await gf(token,`https://gmail.googleapis.com/gmail/v1/users/me/messages/${m.id}?format=full`);const h=headersMap(x.payload),body=decodePart(x.payload).slice(0,30000);out.push({id:x.id,threadId:x.threadId,labelIds:x.labelIds||[],from:h.from||'',to:h.to||'',cc:h.cc||'',fromEmail:emailFrom(h.from||''),toEmail:emailFrom(h.to||''),subject:h.subject||'(제목 없음)',date:h.date||'',snippet:x.snippet||'',body,url:gmailUrl(accountEmail,x.id,x.threadId)})}return out}
function rawMail(to,subject,body){const s=[`To: ${to}`,`Subject: =?UTF-8?B?${Buffer.from(subject||'').toString('base64')}?=`,`MIME-Version: 1.0`,`Content-Type: text/plain; charset=UTF-8`,`Content-Transfer-Encoding: 8bit`,'',body||''].join('\r\n');return Buffer.from(s).toString('base64url')}
async function openaiJSON(prompt){if(!process.env.OPENAI_API_KEY)return null;const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',input:prompt})});if(!r.ok)throw new Error(`OpenAI ${r.status}: ${(await r.text()).slice(0,300)}`);const d=await r.json();const text=(d.output||[]).flatMap(o=>o.content||[]).map(c=>c.text||'').join('').replace(/^```json\s*/,'').replace(/```$/,'').trim();return JSON.parse(text)}

module.exports=async(req,res)=>{try{
  const u=new URL(req.url,origin(req)),action=u.searchParams.get('action')||'status',c=parseCookies(req);
  if(action==='connect'){
    if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return redirect(res,'/?gmail=not_configured');
    const state=crypto.randomBytes(18).toString('hex'),scopes=['openid','email','profile','https://www.googleapis.com/auth/gmail.readonly','https://www.googleapis.com/auth/gmail.compose'].join(' '),q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:`${origin(req)}/api/gmail?action=callback`,response_type:'code',scope:scopes,access_type:'offline',prompt:'consent select_account',include_granted_scopes:'true',state});
    return redirect(res,`https://accounts.google.com/o/oauth2/v2/auth?${q}`,[cookie('gm_state',state,{maxAge:600})]);
  }
  if(action==='callback'){
    const code=u.searchParams.get('code'),state=u.searchParams.get('state');if(!code||!state||state!==c.gm_state)return redirect(res,'/?gmail=auth_error');
    const params=new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',redirect_uri:`${origin(req)}/api/gmail?action=callback`,grant_type:'authorization_code'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)return redirect(res,'/?gmail=token_error');const t=await r.json(),me=await gf(t.access_token,'https://www.googleapis.com/oauth2/v2/userinfo'),key=accountKey(me.email),registry=parseRegistry(c).filter(x=>x.key!==key);registry.push({key,email:me.email,name:me.name||me.email,connectedAt:Date.now()});
    const cs=[cookie(`gm_${key}_access`,t.access_token,{maxAge:Math.max(300,(t.expires_in||3600)-120)}),registryCookie(registry),cookie('gm_state','',{maxAge:0})];if(t.refresh_token)cs.push(cookie(`gm_${key}_refresh`,t.refresh_token,{maxAge:60*60*24*180}));return redirect(res,'/?gmail=connected',cs);
  }
  if(action==='status')return json(res,200,{accounts:parseRegistry(c)});
  const b=req.method==='POST'?await readBody(req):{},registry=parseRegistry(c),key=b.accountKey||u.searchParams.get('accountKey')||registry[0]?.key;if(!key)return json(res,400,{error:'gmail_account_required'});const token=await accountAccess(req,res,key);if(!token)return json(res,401,{error:'gmail_account_not_connected'});const account=registry.find(x=>x.key===key)||{};
  if(action==='search'){const messages=await listMessages(token,b.q||u.searchParams.get('q')||'newer_than:90d',b.maxResults||30,account.email||'');return json(res,200,{account,messages})}
  if(action==='draft'){if(!b.to)return json(res,400,{error:'recipient_required'});const raw=rawMail(b.to,b.subject||'',b.body||''),d=await gf(token,'https://gmail.googleapis.com/gmail/v1/users/me/drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:{raw}})});return json(res,200,{draftId:d.id,messageId:d.message?.id,url:`https://mail.google.com/mail/u/${encodeURIComponent(account.email||'0')}/#drafts`})}
  if(action==='ai-draft'){
    const prompt=`You are TeamGRIT's sales assistant. Write a concise professional Korean sales follow-up email. Return ONLY valid JSON with keys subject and body. Do not invent facts. Use the provided confirmed context only. If information is missing, write a neutral request for discussion rather than making claims.\nCONTEXT:\n${JSON.stringify(b.context||{},null,2).slice(0,30000)}`;
    let draft=await openaiJSON(prompt);if(!draft)draft={subject:`[TeamGRIT] ${b.context?.title||'협의 요청'}`,body:`안녕하세요. TeamGRIT입니다.\n\n${b.context?.summary||'관련하여 논의 가능하신 일정이 있으실지 확인 부탁드립니다.'}\n\n감사합니다.`};return json(res,200,{draft})
  }
  if(action==='disconnect'){const next=registry.filter(x=>x.key!==key),cs=[registryCookie(next),cookie(`gm_${key}_access`,'',{maxAge:0}),cookie(`gm_${key}_refresh`,'',{maxAge:0})];res.setHeader('Set-Cookie',cs);return json(res,200,{ok:true,accounts:next})}
  return json(res,404,{error:'unknown_action'});
}catch(e){return json(res,500,{error:e.message})}}
