const crypto=require('crypto');
function parseCookies(req){const raw=req.headers.cookie||'',out={};raw.split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function cookie(name,value,opts={}){const p=[`${name}=${encodeURIComponent(value)}`,`Path=${opts.path||'/'}`];if(opts.httpOnly!==false)p.push('HttpOnly');if(opts.secure!==false)p.push('Secure');p.push(`SameSite=${opts.sameSite||'Lax'}`);if(opts.maxAge!==undefined)p.push(`Max-Age=${opts.maxAge}`);return p.join('; ')}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
function redirect(res,url,cookies=[]){res.statusCode=302;if(cookies.length)res.setHeader('Set-Cookie',cookies);res.setHeader('Location',url);res.end()}
function origin(req){const proto=(req.headers['x-forwarded-proto']||'https').split(',')[0];return `${proto}://${req.headers.host}`}
async function refresh(refreshToken){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:refreshToken,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req,res){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;const t=await refresh(c.g_refresh);res.setHeader('Set-Cookie',[cookie('g_access',t.access_token,{maxAge:Math.max(300,(t.expires_in||3600)-120)}),cookie('g_refresh',c.g_refresh,{maxAge:60*60*24*30})]);return t.access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);if(r.status===204)return null;return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
function folderId(v=''){const m=String(v).match(/\/folders\/([A-Za-z0-9_-]+)/);return m?m[1]:String(v).trim()}
module.exports=async(req,res)=>{try{const u=new URL(req.url,origin(req)),path=u.searchParams.get('path')||'';
if(path==='auth/google'){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)return redirect(res,'/?google=not_configured');const state=crypto.randomBytes(18).toString('hex'),scopes=['openid','email','profile','https://www.googleapis.com/auth/drive','https://www.googleapis.com/auth/documents','https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/presentations','https://www.googleapis.com/auth/forms.body'].join(' '),q=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:`${origin(req)}/api/auth/callback`,response_type:'code',scope:scopes,access_type:'offline',prompt:'consent',include_granted_scopes:'true',state});return redirect(res,`https://accounts.google.com/o/oauth2/v2/auth?${q}`,[cookie('g_state',state,{maxAge:600})])}
if(path==='auth/callback'){const code=u.searchParams.get('code'),state=u.searchParams.get('state'),c=parseCookies(req);if(!code||!state||state!==c.g_state)return redirect(res,'/?google=auth_error');const params=new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',redirect_uri:`${origin(req)}/api/auth/callback`,grant_type:'authorization_code'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)return redirect(res,'/?google=token_error');const t=await r.json(),cookies=[cookie('g_access',t.access_token,{maxAge:Math.max(300,(t.expires_in||3600)-120)}),cookie('g_state','',{maxAge:0})];if(t.refresh_token)cookies.push(cookie('g_refresh',t.refresh_token,{maxAge:60*60*24*30}));return redirect(res,'/?google=connected',cookies)}
if(path==='auth/status'){const token=await access(req,res);if(!token)return json(res,200,{connected:false,configured:!!(process.env.GOOGLE_CLIENT_ID&&process.env.GOOGLE_CLIENT_SECRET)});const me=await gf(token,'https://www.googleapis.com/oauth2/v2/userinfo');return json(res,200,{connected:true,configured:true,user:{email:me.email,name:me.name}})}
if(path==='auth/logout'){res.setHeader('Set-Cookie',[cookie('g_access','',{maxAge:0}),cookie('g_refresh','',{maxAge:0})]);return json(res,200,{ok:true})}
const token=await access(req,res);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});
if(path==='drive/list'){const fid=folderId(u.searchParams.get('folderId')||'');if(!fid)return json(res,400,{error:'folder_required'});const q=encodeURIComponent(`'${fid}' in parents and trashed=false`),d=await gf(token,`https://www.googleapis.com/drive/v3/files?q=${q}&pageSize=100&fields=files(id,name,mimeType,modifiedTime,webViewLink,size)`);return json(res,200,{folderId:fid,files:d.files||[]})}
return json(res,404,{error:'not_found',path});}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}}
