const crypto=require('crypto');
const OPS_SHEET_ID=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';
const WORK_DOC_ID=process.env.TEAMGRIT_WORK_DOC_ID||'1Z5pJR4v7l9XzgVjALTcRPskkEYJoc_Ii5l6zA3gXqLI';
const MODEL=process.env.TASK_GEMINI_MODEL||'gemini-2.5-flash-lite';
const TASK_SHEET='Tasks';
const HEADERS=['task_id','title','project','owner','due_date','status','source','source_url','created_at','approved_at'];
function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
async function refresh(rt){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:rt,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;return (await refresh(c.g_refresh)).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);if(r.status===204)return null;return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
function clean(v){return v===undefined||v===null?'':String(v).trim()}
function docText(doc){const out=[];function walk(content=[]){for(const b of content){for(const e of b.paragraph?.elements||[])if(e.textRun?.content)out.push(e.textRun.content);for(const row of b.table?.tableRows||[])for(const cell of row.tableCells||[])walk(cell.content||[])}}walk(doc.body?.content||[]);for(const tab of doc.tabs||[])walk(tab.documentTab?.body?.content||[]);return out.join('').trim()}
async function ensureSheet(token){const meta=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}?fields=sheets.properties`);if(!(meta.sheets||[]).some(s=>s.properties?.title===TASK_SHEET))await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}:batchUpdate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests:[{addSheet:{properties:{title:TASK_SHEET}}}]})});const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A1:J2')}`);if(!(d.values||[]).length)await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A1:J1')}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[HEADERS]})})}
async function listTasks(token){await ensureSheet(token);const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A1:J1000')}`),rows=d.values||[],head=rows[0]||HEADERS;return rows.slice(1).filter(r=>clean(r[0])).map(r=>{const o={};head.forEach((h,i)=>o[h]=r[i]??'');return o})}
async function appendTasks(token,tasks){await ensureSheet(token);const now=new Date().toISOString(),values=tasks.map(t=>[`task_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`,clean(t.title),clean(t.project)||'확인 필요',clean(t.owner)||'확인 필요',clean(t.dueDate)||'확인 필요',clean(t.status)||'예정','2026년 팀그릿 업무진행',`https://docs.google.com/document/d/${WORK_DOC_ID}/edit`,now,now]);if(values.length)await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A:J')}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})});return values.length}
function cleanJSON(t=''){return t.replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim()}
async function gemini(prompt){if(!process.env.GEMINI_API_KEY)throw new Error('GEMINI_API_KEY 미설정');const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(MODEL)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',temperature:.15}})});if(!r.ok)throw new Error(`Gemini ${r.status}: ${(await r.text()).slice(0,300)}`);const d=await r.json(),txt=(d.candidates?.[0]?.content?.parts||[]).map(p=>p.text||'').join('');return JSON.parse(cleanJSON(txt))}
module.exports=async(req,res)=>{try{const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action')||'list';if(req.method==='GET'&&action==='list')return json(res,200,{tasks:await listTasks(token),source:'TeamGRIT Ops 운영 데이터'});if(req.method==='POST'&&action==='analyze'){const b=await body(req);let work='';try{work=docText(await gf(token,`https://docs.googleapis.com/v1/documents/${WORK_DOC_ID}?includeTabsContent=true`))}catch(e){return json(res,200,{tasks:[],modelUsed:null,sources:{workDoc:'연결 안 됨',systemDev:'연결 안 됨'},error:'2026년 팀그릿 업무진행 문서를 읽을 수 없습니다.'})}const memo=clean(b.memo);if(!memo)return json(res,400,{error:'memo_required'});const prompt=`TeamGRIT 내부 업무 자동화용 업무 추출기다. 아래 사용자의 회의/업무 메모와 실제 회사 업무진행 문서만 근거로 업무 후보를 만든다. 문서나 메모에 없는 프로젝트, 담당자, 기한, 상태를 절대 추정하거나 샘플로 채우지 마라. 모르는 값은 빈 문자열로 둔다. 실제 실행 전에 사용자가 검토·승인한다. JSON만 반환: {"tasks":[{"title":string,"project":string,"owner":string,"dueDate":string,"status":string,"reason":string,"sourceEvidence":string}]}. 업무는 중복 없이 구체적인 실행 단위로 작성한다.\n\n[사용자 메모]\n${memo}\n\n[실제 기준 문서: 2026년 팀그릿 업무진행]\n${work.slice(0,80000)}`;const out=await gemini(prompt);return json(res,200,{tasks:out.tasks||[],modelUsed:MODEL,sources:{workDoc:`https://docs.google.com/document/d/${WORK_DOC_ID}/edit`,systemDev:'연결 안 됨'}})}if(req.method==='POST'&&action==='register'){const b=await body(req),approved=(b.tasks||[]).filter(t=>t&&t.approved===true);if(!approved.length)return json(res,400,{error:'approved_tasks_required'});const count=await appendTasks(token,approved);return json(res,200,{ok:true,count,tasks:await listTasks(token)})}return json(res,404,{error:'not_found'});}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}}
