require('./_lib/gemini-model-compat')();
const base=require('./tasks-v2');
const central=require('./_lib/central-entities');
const {gemini,clean,arr}=require('./_lib/source-corpus-all');

const OPS=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';

function cookies(req){const o={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return o}
async function access(req){const c=cookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:c.g_refresh,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('Google token refresh failed');return (await r.json()).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function sheetRows(token,name,range){const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent(`${name}!${range}`)}`).catch(()=>({values:[]})),rows=d.values||[];if(rows.length<2)return[];const head=rows[0];return rows.slice(1).filter(r=>r.some(v=>String(v||'').trim())).map(r=>{const o={};head.forEach((h,i)=>o[h]=r[i]??'');return o})}
function norm(v){return clean(v).toLowerCase().replace(/[^a-z0-9가-힣]+/g,' ').replace(/\s+/g,' ').trim()}
function toks(v){return [...new Set(norm(v).split(' ').filter(x=>x.length>=2))]}
function overlap(a,b){const A=toks(a),B=new Set(toks(b));if(!A.length||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(A.length,B.size)}
function taskSimilarity(a,b){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 1;if((A.includes(B)||B.includes(A))&&Math.min(A.length,B.length)>=7)return .9;return overlap(A,B)}
function ids(v){return [...new Set(String(v||'').split(/[\s,;|]+/).map(clean).filter(Boolean))]}
function sourceId(s){return clean(s.source_id||s.sourceId||s.id)}
function sourceTitle(s){return clean(s.title||s.name||s.file_name||s.fileName||sourceId(s))}
function sourceText(s){return Object.values(s||{}).map(clean).filter(Boolean).join(' ')}
function projectText(p){return [p.name,p.customer,p.manual_category,p.source_category,p.summary,p.source_evidence,p.evidence].map(clean).join(' ')}
function projectSourceIds(p){return ids(p.source_ids||p.sourceIds)}
function factText(f){return [f.subject,f.fact,f.evidence].map(clean).join(' ')}
function factSourceIds(f){return ids(f.source_ids||f.sourceIds)}
function score(query,text){const q=norm(query),t=norm(text);if(!q||!t)return 0;let s=overlap(q,t);for(const token of toks(q)){if(token.length>=4&&t.includes(token))s+=.035}return s}
function rank(query,items,textFn,limit=20,min=.03){return items.map(item=>({item,score:score(query,textFn(item))})).filter(x=>x.score>=min).sort((a,b)=>b.score-a.score).slice(0,limit)}
function sourceMap(sources){const m=new Map();for(const s of sources){const id=sourceId(s);if(id)m.set(id,s)}return m}
function exactProject(projects,name){const n=norm(name);return projects.find(p=>norm(p.name)===n)||null}
function buildFocusedContext(memo,projects,facts,sources,tasks){
  const rankedProjects=rank(memo,projects,projectText,8,.025);
  const rankedFacts=rank(memo,facts,factText,40,.025);
  const wanted=new Set();
  for(const x of rankedProjects)for(const id of projectSourceIds(x.item))wanted.add(id);
  for(const x of rankedFacts)for(const id of factSourceIds(x.item))wanted.add(id);
  const rankedSources=rank(memo,sources,sourceText,25,.02);
  for(const x of rankedSources)wanted.add(sourceId(x.item));
  const relatedSources=sources.filter(s=>wanted.has(sourceId(s))).slice(0,40);
  const relatedTasks=rank(memo,tasks,t=>[t.title,t.project,t.owner,t.source].map(clean).join(' '),60,.015).map(x=>x.item);
  const lines=[];
  for(const x of rankedProjects)lines.push(`[PROJECT] ${clean(x.item.name)} | score:${x.score.toFixed(3)} | 고객:${clean(x.item.customer)} | 상태:${clean(x.item.manual_status||x.item.source_status)} | 분류:${clean(x.item.manual_category||x.item.source_category)} | 요약:${clean(x.item.summary)} | 근거:${clean(x.item.source_evidence||x.item.evidence)} | sourceIds:${projectSourceIds(x.item).join(',')}`);
  for(const x of rankedFacts)lines.push(`[FACT] ${clean(x.item.subject)} | ${clean(x.item.fact)} | score:${x.score.toFixed(3)} | 근거:${clean(x.item.evidence)} | sourceIds:${factSourceIds(x.item).join(',')}`);
  for(const s of relatedSources)lines.push(`[SOURCE] ${sourceId(s)} | ${sourceTitle(s)} | ${clean(s.root_source||s.rootSource)} | ${clean(s.url||s.source_url||s.webViewLink)}`);
  for(const t of relatedTasks)lines.push(`[EXISTING_TASK] ${clean(t.title)} | 프로젝트:${clean(t.project)} | 담당자:${clean(t.owner)} | 기한:${clean(t.due_date)} | 상태:${clean(t.status)} | sourceIds:${clean(t.source_ids)}`);
  return {text:lines.join('\n').slice(0,120000),rankedProjects,rankedFacts,relatedSources,relatedTasks};
}
async function context(token,memo){const [projects,facts,sources,tasks]=await Promise.all([central.list(token,'Projects').catch(()=>[]),central.list(token,'ProductFacts').catch(()=>[]),sheetRows(token,'Sources','A1:O5000'),sheetRows(token,'Tasks','A1:R5000')]);const validIds=new Set(sources.map(sourceId).filter(Boolean)),focused=buildFocusedContext(memo,projects,facts,sources,tasks);return {projects,facts,sources,tasks,validIds,sourceById:sourceMap(sources),focused,totalSourceCount:sources.length,existingTaskCount:tasks.length}}
function normalizeTasks(data,ctx){return arr(data?.tasks).map(t=>({title:clean(t.title),project:clean(t.project),owner:clean(t.owner),dueDate:clean(t.dueDate),status:clean(t.status)||'예정',reason:clean(t.reason),sourceEvidence:clean(t.sourceEvidence),sourceIds:arr(t.sourceIds).map(clean).filter(id=>ctx.validIds.has(id)),duplicateStatus:clean(t.duplicateStatus)||'new'})).filter(t=>t.title)}
function resolveProject(task,ctx,memo){const knownAi=exactProject(ctx.projects,task.project);let best=null,bestScore=0,bestReason='';const taskQuery=[task.title,task.reason,task.sourceEvidence].join(' '),taskIds=new Set(task.sourceIds||[]);for(const p of ctx.projects){const pIds=projectSourceIds(p),shared=pIds.filter(id=>taskIds.has(id));let s=score(taskQuery,projectText(p));if(shared.length)s+=2+Math.min(1,shared.length*.25);if(knownAi&&norm(knownAi.name)===norm(p.name))s+=.35;if(norm(memo).includes(norm(p.name))&&norm(p.name).length>=4)s+=.4;if(s>bestScore){best=p;bestScore=s;bestReason=shared.length?`후보 근거 Source ${shared.slice(0,3).join(', ')}가 프로젝트 근거와 연결됨`:`업무 문맥과 프로젝트 근거 유사도 ${s.toFixed(2)}`}}
  if(!best||bestScore<.16)return {project:'',projectEvidence:'명확한 프로젝트 근거를 찾지 못해 확인 필요',projectScore:bestScore};
  return {project:clean(best.name),projectEvidence:bestReason,projectScore:bestScore};
}
function enrichTask(task,ctx,memo){const rp=resolveProject(task,ctx,memo),titles=(task.sourceIds||[]).map(id=>({id,title:sourceTitle(ctx.sourceById.get(id)||{}),url:clean((ctx.sourceById.get(id)||{}).url||(ctx.sourceById.get(id)||{}).source_url)}));return {...task,...rp,sourceTitles:titles,decisionSummary:`${rp.project?`프로젝트 '${rp.project}' 근거 확인`:'프로젝트 확인 필요'} · Source ${titles.length}개 근거 사용`}}
function duplicateCheck(tasks,ctx){const kept=[],checks=[],suppressed=[];for(const t of tasks){let best=null,bestScore=0;for(const e of ctx.tasks){const s=taskSimilarity(t.title,e.title),sameProject=!t.project||!e.project||norm(t.project)===norm(e.project);if(sameProject&&s>bestScore){best=e;bestScore=s}}if(best&&bestScore>=.72){suppressed.push(t);checks.push({title:t.title,result:'duplicate',matchedTask:clean(best.title),score:bestScore})}else{kept.push({...t,duplicateStatus:'new'});checks.push({title:t.title,result:'new',matchedTask:'',score:bestScore})}}return {kept,checks,suppressed}}
async function callAdk(memo,ctx){const baseUrl=String(process.env.TEAMGRIT_AGENT_URL||'').replace(/\/$/,'');if(!baseUrl)throw new Error('agent_runtime_not_configured');const headers={'Content-Type':'application/json'};if(process.env.TEAMGRIT_AGENT_TOKEN)headers.Authorization=`Bearer ${process.env.TEAMGRIT_AGENT_TOKEN}`;const r=await fetch(`${baseUrl}/teamgrit/analyze`,{method:'POST',headers,body:JSON.stringify({memo,centralContext:ctx.focused.text,validSourceIds:[...ctx.validIds]})});if(!r.ok)throw new Error(`ADK runtime ${r.status}: ${(await r.text()).slice(0,400)}`);return r.json()}
async function runBuiltIn(memo,ctx){const projectNames=ctx.focused.rankedProjects.map(x=>clean(x.item.name));const prompt=`너는 TeamGRIT 업무 에이전트다. 아래는 전체 회사 자료가 아니라 사용자 메모와 관련도가 높은 중앙 근거만 선별한 컨텍스트다. 반드시 이 근거 안에서만 판단한다.\n1) 메모를 실행 가능한 업무로 분해한다.\n2) 관련 PROJECT/FACT/SOURCE를 근거로 연결한다.\n3) project는 반드시 제공된 PROJECT의 정확한 이름만 사용하거나, 불명확하면 빈 문자열로 둔다.\n4) 담당자/기한도 메모 또는 근거에 명시되지 않으면 빈 문자열로 둔다.\n5) sourceIds는 제공된 SOURCE/PROJECT/FACT에 실제 등장한 ID만 사용한다.\n6) 기존 업무와 겹치면 duplicateStatus=duplicate.\nJSON만 반환한다. 형식: {"tasks":[{"title":string,"project":string,"owner":string,"dueDate":string,"status":string,"reason":string,"sourceEvidence":string,"sourceIds":[string],"duplicateStatus":"new"|"duplicate"}],"trace":{"reasoningSummary":string}}.\n\n[사용자 메모]\n${memo}\n\n[사용 가능한 프로젝트명]\n${projectNames.join('\n')||'없음'}\n\n[관련 중앙 근거]\n${ctx.focused.text}`;const ai=await gemini(prompt);return {...ai.data,modelUsed:ai.modelUsed}}
async function analyze(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const b=await readBody(req),memo=clean(b.memo);if(!memo)return json(res,400,{error:'memo_required'});const ctx=await context(token,memo);if(!ctx.focused.text)return json(res,200,{tasks:[],modelUsed:null,error:'관련 중앙 근거를 찾지 못했습니다. 먼저 원본을 동기화하거나 메모를 더 구체적으로 작성해주세요.'});let data,runtime='google-adk',fallbackReason='';try{data=await callAdk(memo,ctx)}catch(e){runtime='teamgrit-agent';fallbackReason=String(e?.message||e);data=await runBuiltIn(memo,ctx)}const normalized=normalizeTasks(data,ctx).map(t=>enrichTask(t,ctx,memo)),aiDup=normalized.filter(t=>t.duplicateStatus==='duplicate'),candidates=normalized.filter(t=>t.duplicateStatus!=='duplicate'),dup=duplicateCheck(candidates,ctx),tasks=dup.kept,suppressed=aiDup.length+dup.suppressed.length,usedIds=[...new Set(tasks.flatMap(t=>t.sourceIds||[]))],matchedProjects=[...new Set(tasks.map(t=>t.project).filter(Boolean))];const trace={matchedProjects,relevantSourceCount:ctx.focused.relatedSources.length,usedSourceCount:usedIds.length,totalSourceCount:ctx.totalSourceCount,existingTaskChecks:dup.checks,proposedCount:tasks.length,suppressedDuplicateCount:suppressed,existingTaskCount:ctx.existingTaskCount,reasoningSummary:clean(data?.trace?.reasoningSummary),relevantSources:ctx.focused.relatedSources.slice(0,12).map(s=>({id:sourceId(s),title:sourceTitle(s),url:clean(s.url||s.source_url)})),steps:[{name:'관련 근거 검색',status:'완료',detail:`전체 Source ${ctx.totalSourceCount}개 중 관련 Source ${ctx.focused.relatedSources.length}개 선별`},{name:'프로젝트 확정',status:'완료',detail:`근거 연결로 프로젝트 ${matchedProjects.length}개 확정`},{name:'기존 업무 비교',status:'완료',detail:`기존 Tasks ${ctx.existingTaskCount}개와 비교 · 중복 ${suppressed}개 제외`},{name:'신규 업무 제안',status:'완료',detail:`실제 판단에 Source ${usedIds.length}개 사용 · 신규 ${tasks.length}개 제안`} ]};return json(res,200,{tasks,trace,modelUsed:data?.modelUsed||process.env.TEAMGRIT_AGENT_MODEL||'gemini-3.8-flash',runtime,agentRuntime:true,externalAdk:runtime==='google-adk',fallbackReason:runtime==='teamgrit-agent'?fallbackReason:'',sourceCount:ctx.totalSourceCount,relevantSourceCount:ctx.focused.relatedSources.length,usedSourceCount:usedIds.length,existingTaskCount:ctx.existingTaskCount,usingCentralCache:true})}

async function taskById(token,id){const rows=await sheetRows(token,'Tasks','A1:R5000');return rows.find(t=>clean(t.task_id)===clean(id))||null}

const RESULT_KINDS=new Set(['auto','email','message','document','spreadsheet','presentation','pdf','research','code','image','design','execution']);
function normalizeResultKind(v){const k=clean(v).toLowerCase();return RESULT_KINDS.has(k)?k:'auto'}
function artifactData(v){try{return typeof v==='string'?JSON.parse(v||'{}'):(v||{})}catch{return {}}}
function driveFolderId(v=''){const m=String(v).match(/\/folders\/([A-Za-z0-9_-]+)/);return m?m[1]:''}
async function projectFolderId(token,projectName){if(!clean(projectName))return '';const projects=await central.list(token,'Projects').catch(()=>[]),p=projects.find(x=>norm(x.name)===norm(projectName));return driveFolderId(p?.drive_url||p?.driveUrl||'')}
async function moveToFolder(token,fileId,folderId){if(!fileId||!folderId)return;const meta=await gf(token,\`https://www.googleapis.com/drive/v3/files/\${encodeURIComponent(fileId)}?fields=parents\`).catch(()=>null),parents=(meta?.parents||[]).join(',');let url=\`https://www.googleapis.com/drive/v3/files/\${encodeURIComponent(fileId)}?addParents=\${encodeURIComponent(folderId)}&fields=id,parents\`;if(parents)url+=\`&removeParents=\${encodeURIComponent(parents)}\`;await gf(token,url,{method:'PATCH'}).catch(()=>{})}
async function createDoc(token,title,content,folderId=''){const d=await gf(token,'https://docs.googleapis.com/v1/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title||'TeamGRIT 결과물'})});if(content)await gf(token,\`https://docs.googleapis.com/v1/documents/\${d.documentId}:batchUpdate\`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests:[{insertText:{location:{index:1},text:String(content)}}]})});await moveToFolder(token,d.documentId,folderId);return {id:d.documentId,url:\`https://docs.google.com/document/d/\${d.documentId}/edit\`,kind:'document'}}
async function createSheet(token,title,data,folderId=''){const rows=Array.isArray(data.rows)?data.rows:[],s=await gf(token,'https://sheets.googleapis.com/v4/spreadsheets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({properties:{title:title||'TeamGRIT 결과물'},sheets:[{properties:{title:'결과'}}]})});if(rows.length)await gf(token,\`https://sheets.googleapis.com/v4/spreadsheets/\${s.spreadsheetId}/values/\${encodeURIComponent('결과!A1')}?valueInputOption=RAW\`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:rows.map(r=>Array.isArray(r)?r:[r])})});await moveToFolder(token,s.spreadsheetId,folderId);return {id:s.spreadsheetId,url:\`https://docs.google.com/spreadsheets/d/\${s.spreadsheetId}/edit\`,kind:'spreadsheet'}}
function safeObjectId(prefix,i){return (prefix+String(i)+'_'+Date.now().toString(36)).replace(/[^A-Za-z0-9_]/g,'').slice(0,40)}
async function createSlides(token,title,data,folderId=''){const p=await gf(token,'https://slides.googleapis.com/v1/presentations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title||'TeamGRIT 결과물'})}),pid=p.presentationId,existing=(p.slides||[]).map(s=>s.objectId),slides=Array.isArray(data.slides)&&data.slides.length?data.slides:[{title,body:data.content||''}],requests=[];slides.slice(0,20).forEach((s,i)=>{const slideId=safeObjectId('slide',i),titleId=safeObjectId('title',i),bodyId=safeObjectId('body',i);requests.push({createSlide:{objectId:slideId,slideLayoutReference:{predefinedLayout:'BLANK'}}},{createShape:{objectId:titleId,shapeType:'TEXT_BOX',elementProperties:{pageObjectId:slideId,size:{width:{magnitude:640,unit:'PT'},height:{magnitude:60,unit:'PT'}},transform:{scaleX:1,scaleY:1,translateX:40,translateY:35,unit:'PT'}}}},{insertText:{objectId:titleId,text:clean(s.title)||\`Slide \${i+1}\`}},{createShape:{objectId:bodyId,shapeType:'TEXT_BOX',elementProperties:{pageObjectId:slideId,size:{width:{magnitude:640,unit:'PT'},height:{magnitude:360,unit:'PT'}},transform:{scaleX:1,scaleY:1,translateX:40,translateY:115,unit:'PT'}}}},{insertText:{objectId:bodyId,text:clean(s.body||s.content)}})});for(const id of existing)requests.push({deleteObject:{objectId:id}});if(requests.length)await gf(token,\`https://slides.googleapis.com/v1/presentations/\${pid}:batchUpdate\`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests})});await moveToFolder(token,pid,folderId);return {id:pid,url:\`https://docs.google.com/presentation/d/\${pid}/edit\`,kind:'presentation'}}
async function materializeResult(token,r){const kind=normalizeResultKind(r.artifact_kind),data=artifactData(r.artifact_data),folderId=await projectFolderId(token,r.project_id),title=clean(r.title)||'TeamGRIT 결과물';if(kind==='document'||kind==='research'){const f=await createDoc(token,title,r.content,folderId);return {...f,status:'파일 생성 완료'}}if(kind==='spreadsheet'){const f=await createSheet(token,title,data,folderId);return {...f,status:'파일 생성 완료'}}if(kind==='presentation'){const f=await createSlides(token,title,{...data,content:r.content},folderId);return {...f,status:'파일 생성 완료'}}if(kind==='pdf'){const f=await createDoc(token,title,r.content,folderId);return {...f,url:\`https://docs.google.com/document/d/\${f.id}/export?format=pdf\`,kind:'pdf',status:'PDF 링크 생성 완료'}}if(kind==='email'||kind==='message')return {kind,status:'발송 전 확정 초안'};if(kind==='code')return {kind,status:'코드 초안 확정 · GitHub 실행 연결 필요'};if(kind==='image'||kind==='design')return {kind,status:'이미지/디자인 브리프 확정 · 생성 실행 연결 필요'};if(kind==='execution')return {kind,status:'실행 결과 형식 확정 · 별도 실행 필요'};return {kind:kind||'document',status:'초안 확정'}}
function resultPrompt(task,ctx,preferredKind='auto'){return \`너는 TeamGRIT 실무 결과물 에이전트다. 업무를 보고 결과물 유형을 판단하고 실제 검토 가능한 초안을 만든다. preferredKind가 auto가 아니면 그 유형을 우선한다.
허용 kind: email, message, document, spreadsheet, presentation, pdf, research, code, image, design, execution.
- email/message: 바로 보낼 수 있는 본문. 수신자/사실이 없으면 [확인 필요].
- document/research/pdf: 제목과 완성된 본문.
- spreadsheet: content에는 표 설명, artifactData.rows에는 2차원 배열을 넣는다.
- presentation: content에는 발표 개요, artifactData.slides에는 [{"title":string,"body":string}] 배열을 넣는다.
- code: content에는 변경 요약, artifactData에는 {"language":string,"filename":string,"code":string}.
- image/design: content에는 디자인 브리프, artifactData에는 {"prompt":string,"aspectRatio":string,"requirements":[string]}. 이미지 자체는 승인 이후 별도 생성기로 넘길 수 있게 상세히 쓴다.
- execution: content에는 실행 결과로 확인해야 할 체크리스트와 성공 기준.
원문과 중앙 근거에 없는 사실, 일정, 담당자, 수치, 확정사항은 만들지 말고 [확인 필요]로 표시한다.
JSON만 반환한다. 형식: {"kind":string,"type":string,"title":string,"content":string,"summary":string,"artifactData":object}.

[선호 유형]
\${preferredKind}

[업무]
업무명: \${clean(task.title)}
프로젝트: \${clean(task.project)}
담당자: \${clean(task.owner)}
기한: \${clean(task.due_date)}
상태: \${clean(task.status)}
출처: \${clean(task.source)}
출처 링크: \${clean(task.source_url)}
선행 업무: \${clean(task.predecessor_task_ids)}

[관련 중앙 근거]
\${ctx.focused.text}\`}
async function generateResult(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req),taskId=clean(b.task_id||b.id),preferredKind=normalizeResultKind(b.kind||'auto');if(!taskId)return json(res,400,{error:'task_id_required'});const task=await taskById(token,taskId);if(!task)return json(res,404,{error:'task_not_found'});const ctx=await context(token,[task.title,task.project,task.source].join(' '));const ai=await gemini(resultPrompt(task,ctx,preferredKind));const d=ai.data||{},kind=normalizeResultKind(d.kind||preferredKind)==='auto'?'document':normalizeResultKind(d.kind||preferredKind),type=clean(d.type)||kind,title=clean(d.title)||\`\${clean(task.title)} 결과물 초안\`,content=clean(d.content),summary=clean(d.summary),artifact=d.artifactData||{};if(!content&&!Object.keys(artifact).length)return json(res,500,{error:'result_generation_empty'});const result=central.result({projectId:clean(task.project),taskId,type,title,fileUrl:'',status:'초안',content,reviewStatus:'검토 대기',sourceTaskId:taskId,artifactKind:kind,artifactData:artifact,executorStatus:'검토 대기'});await central.append(token,'Results',[result]);const requestedBy=await central.userEmail(token),review=central.reviewRequest({targetType:'Result',targetId:result.result_id,taskId,project:clean(task.project),title,status:'검토 대기',requestedBy,note:summary});await central.append(token,'ReviewRequests',[review]);return json(res,200,{ok:true,result,review,modelUsed:ai.modelUsed,kind});}
async function listReviews(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const [results,reviews]=await Promise.all([central.list(token,'Results'),central.list(token,'ReviewRequests')]);const pending=results.filter(r=>['검토 대기','수정 필요'].includes(clean(r.review_status))).sort((a,b)=>String(b.updated_at||b.created_at).localeCompare(String(a.updated_at||a.created_at)));return json(res,200,{results:pending,reviews,allResults:results});}
async function reviewResult(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req),resultId=clean(b.result_id||b.id),action=clean(b.action);if(!resultId)return json(res,400,{error:'result_id_required'});const results=await central.list(token,'Results'),idx=results.findIndex(r=>clean(r.result_id)===resultId);if(idx<0)return json(res,404,{error:'result_not_found'});const now=new Date().toISOString(),reviewer=await central.userEmail(token),r={...results[idx]};if(b.content!==undefined)r.content=String(b.content);if(b.title!==undefined)r.title=clean(b.title);if(b.artifactData!==undefined)r.artifact_data=typeof b.artifactData==='string'?b.artifactData:JSON.stringify(b.artifactData||{});r.updated_at=now;let materialized=null;if(action==='approve'){materialized=await materializeResult(token,r);r.review_status='승인됨';r.status='완료';r.approved_by=reviewer;r.approved_at=now;r.executor_status=materialized.status||'확정';if(materialized.url)r.file_url=materialized.url}else if(action==='request_changes'){r.review_status='수정 필요';r.status='초안';r.executor_status='수정 대기'}else return json(res,400,{error:'invalid_review_action'});results[idx]=r;await central.replace(token,'Results',results);const reviews=await central.list(token,'ReviewRequests'),ri=reviews.findIndex(x=>clean(x.target_id)===resultId&&['검토 대기','수정 필요'].includes(clean(x.status)));if(ri>=0){reviews[ri]={...reviews[ri],status:action==='approve'?'승인됨':'수정 필요',reviewed_by:reviewer,reviewed_at:now,note:clean(b.note)||reviews[ri].note};await central.replace(token,'ReviewRequests',reviews)}if(action==='approve'){const approval=central.approval({targetType:'Result',targetId:resultId,action:'결과물 승인·확정',approvedBy:reviewer,source:'앱 내부 검토함',note:\`\${clean(r.title)} · \${clean(r.artifact_kind)}\`});await central.append(token,'Approvals',[approval])}return json(res,200,{ok:true,result:r,materialized});}

module.exports=async(req,res)=>{try{const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action');if(req.method==='POST'&&action==='analyze')return await analyze(req,res);if(req.method==='POST'&&action==='generate-result')return await generateResult(req,res);if(req.method==='GET'&&action==='reviews')return await listReviews(req,res);if(req.method==='POST'&&action==='review-result')return await reviewResult(req,res);return base(req,res)}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}};
