require('./_lib/gemini-model-compat')();
const base=require('./tasks');
const OPS=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';
function cookies(req){const o={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return o}
async function access(req){const c=cookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:c.g_refresh,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('Google token refresh failed');return (await r.json()).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function deleteTask(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req),id=String(b.task_id||b.id||'').trim();if(!id)return json(res,400,{error:'task_id_required'});const range=encodeURIComponent('Tasks!A1:L5000'),d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}`),rows=d.values||[];if(rows.length<2)return json(res,404,{error:'task_not_found'});const head=rows[0],kept=[head,...rows.slice(1).filter(r=>String(r[0]||'').trim()!==id)];if(kept.length===rows.length)return json(res,404,{error:'task_not_found'});await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}:clear`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent('Tasks!A1:L'+kept.length)}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:kept})});return json(res,200,{ok:true,deleted:id});}
module.exports=async(req,res)=>{try{const u=new URL(req.url,`https://${req.headers.host}`);if(req.method==='POST'&&u.searchParams.get('action')==='delete')return await deleteTask(req,res);return base(req,res)}catch(e){return json(res,500,{error:e.message})}};
