require('./_lib/gemini-model-compat')();
const crypto=require('crypto');
const {collectCorpus,contextText,gemini,clean,arr}=require('./_lib/source-corpus-all');
const OPS_SHEET_ID=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';
const TASK_SHEET='Tasks';
const HEADERS=['task_id','title','project','owner','due_date','status','source','source_url','source_ids','created_at','approved_at','updated_at'];
function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>-1)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
async function refresh(rt){const params=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:rt,grant_type:'refresh_token'});const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:params});if(!r.ok)throw new Error('Google token refresh failed');return r.json()}
async function access(req){const c=parseCookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;return (await refresh(c.g_refresh)).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);if(r.status===204)return null;return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
async function ensureSheet(token){const meta=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}?fields=sheets.properties`);if(!(meta.sheets||[]).some(s=>s.properties?.title===TASK_SHEET))await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}:batchUpdate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests:[{addSheet:{properties:{title:TASK_SHEET}}}]})});const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A1:L1')}`).catch(()=>({values:[]})),row=(d.values||[])[0]||[];if(HEADERS.some((h,i)=>row[i]!==h)||row.length!==HEADERS.length)await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A1:L1')}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[HEADERS]})})}
async function listTasks(token){await ensureSheet(token);const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A1:L5000')}`),rows=d.values||[],head=rows[0]||HEADERS;return rows.slice(1).filter(r=>clean(r[0])).map(r=>{const o={};head.forEach((h,i)=>o[h]=r[i]??'');return o})}
async function sourceMap(token){const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent('Sources!A1:O5000')}`).catch(()=>({values:[]})),rows=d.values||[];if(rows.length<2)return new Map();const head=rows[0],map=new Map();for(const r of rows.slice(1)){const o={};head.forEach((h,i)=>o[h]=r[i]??'');if(o.source_id)map.set(o.source_id,o)}return map}
async function appendTasks(token,tasks){await ensureSheet(token);const now=new Date().toISOString(),sources=await sourceMap(token),values=[];for(const t of tasks){const ids=arr(t.sourceIds||t.source_ids).map(clean).filter(Boolean),refs=ids.map(id=>sources.get(id)).filter(Boolean),source=refs.length?[...new Set(refs.map(r=>r.root_source||r.title).filter(Boolean))].join(' / '):'실제 원본 자료',sourceUrl=refs[0]?.url||'';values.push([`task_${Date.now()}_${crypto.randomBytes(3).toString('hex')}`,clean(t.title),clean(t.project)||'확인 필요',clean(t.owner)||'확인 필요',clean(t.dueDate||t.due_date)||'확인 필요',clean(t.status)||'예정',source,sourceUrl,ids.join(','),now,now,now])}if(values.length)await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS_SHEET_ID}/values/${encodeURIComponent(TASK_SHEET+'!A:L')}:append?valueInputOption=RAW&insertDataOption=INSERT_ROWS`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})});return values.length}
module.exports=async(req,res)=>{try{const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action')||'list';if(req.method==='GET'&&action==='list')return json(res,200,{tasks:await listTasks(token),source:'TeamGRIT Ops 운영 데이터'});if(req.method==='POST'&&action==='analyze'){const b=await body(req),memo=clean(b.memo);if(!memo)return json(res,400,{error:'memo_required'});const corpus=await collectCorpus(token),missing=corpus.required.filter(r=>r.status!=='연결됨');if(missing.length)return json(res,200,{tasks:[],modelUsed:null,sources:corpus.required,error:missing.map(r=>`${r.title}: 연결 안 됨`).join(', ')});const context=contextText(corpus),prompt=`TeamGRIT 내부 업무 자동화용 업무 추출기다. 사용자의 메모와 아래 최신 실제 회사 원본만 근거로 업무 후보를 만든다. 원본은 '2026년 팀그릿 업무진행', '시스템개발팀', 그리고 두 문서에서 연결된 Drive 자료다. 원본이나 메모에 없는 프로젝트, 담당자, 기한, 상태를 추정하지 마라. 모르는 값은 빈 문자열. sourceIds에는 직접 근거가 되는 SOURCE id만 넣는다. JSON만 반환: {"tasks":[{"title":string,"project":string,"owner":string,"dueDate":string,"status":string,"reason":string,"sourceEvidence":string,"sourceIds":[string]}]}.\n\n[사용자 메모]\n${memo}\n\n[최신 실제 회사 원본]\n${context}`;const ai=await gemini(prompt),validIds=new Set(corpus.sources.map(s=>s.sourceId));const tasks=arr(ai.data?.tasks).map(t=>({title:clean(t.title),project:clean(t.project),owner:clean(t.owner),dueDate:clean(t.dueDate),status:clean(t.status),reason:clean(t.reason),sourceEvidence:clean(t.sourceEvidence),sourceIds:arr(t.sourceIds).map(clean).filter(id=>validIds.has(id))})).filter(t=>t.title),partial=corpus.sources.filter(s=>s.readStatus==='일부 읽음').length,unreadable=corpus.sources.filter(s=>s.readStatus==='연결 안 됨').length;return json(res,200,{tasks,modelUsed:ai.modelUsed,sources:corpus.required,sourceCount:corpus.sources.length,fullRead:corpus.sources.length-partial-unreadable,partialRead:partial,unreadable})}if(req.method==='POST'&&action==='register'){const b=await body(req),approved=arr(b.tasks).filter(t=>t&&t.approved===true);if(!approved.length)return json(res,400,{error:'approved_tasks_required'});const count=await appendTasks(token,approved);return json(res,200,{ok:true,count,tasks:await listTasks(token)})}return json(res,404,{error:'not_found'})}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}};
