require('./_lib/gemini-model-compat')();
const base=require('./tasks');
const central=require('./_lib/central-entities');
const {gemini,clean,arr}=require('./_lib/source-corpus-all');
const OPS=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';
const TASK_HEADERS=['task_id','title','project','owner','due_date','status','source','source_url','source_ids','created_at','approved_at','updated_at'];
function cookies(req){const o={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return o}
async function access(req){const c=cookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:c.g_refresh,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('Google token refresh failed');return (await r.json()).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function deleteTask(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req),id=String(b.task_id||b.id||'').trim();if(!id)return json(res,400,{error:'task_id_required'});const range=encodeURIComponent('Tasks!A1:L5000'),d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}`),rows=d.values||[];if(rows.length<2)return json(res,404,{error:'task_not_found'});const head=rows[0],kept=[head,...rows.slice(1).filter(r=>String(r[0]||'').trim()!==id)];if(kept.length===rows.length)return json(res,404,{error:'task_not_found'});await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}:clear`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent('Tasks!A1:L'+kept.length)}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:kept})});return json(res,200,{ok:true,deleted:id});}
async function updateTask(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req),id=String(b.task_id||b.id||'').trim();if(!id)return json(res,400,{error:'task_id_required'});const range=encodeURIComponent('Tasks!A1:L5000'),d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}`),rows=d.values||[];if(rows.length<2)return json(res,404,{error:'task_not_found'});const head=rows[0].length?rows[0]:TASK_HEADERS,rowIndex=rows.slice(1).findIndex(r=>String(r[0]||'').trim()===id);if(rowIndex<0)return json(res,404,{error:'task_not_found'});const current={};head.forEach((h,i)=>current[h]=rows[rowIndex+1]?.[i]??'');const allowed={title:b.title,project:b.project,owner:b.owner,due_date:b.due_date??b.dueDate,status:b.status};for(const [k,v] of Object.entries(allowed))if(v!==undefined)current[k]=String(v).trim();current.updated_at=new Date().toISOString();const values=TASK_HEADERS.map(h=>current[h]??''),sheetRow=rowIndex+2;await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent(`Tasks!A${sheetRow}:L${sheetRow}`)}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[values]})});return json(res,200,{ok:true,task:current});}
async function sheetRows(token,name,range){const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent(`${name}!${range}`)}`).catch(()=>({values:[]})),rows=d.values||[];if(rows.length<2)return[];const head=rows[0];return rows.slice(1).filter(r=>r.some(v=>String(v||'').trim())).map(r=>{const o={};head.forEach((h,i)=>o[h]=r[i]??'');return o})}
function norm(v){return clean(v).toLowerCase().replace(/[^a-z0-9가-힣]+/g,' ').replace(/\s+/g,' ').trim()}
function tokens(v){return new Set(norm(v).split(' ').filter(x=>x.length>=2))}
function overlap(a,b){const A=tokens(a),B=tokens(b);if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(A.size,B.size)}
function taskSimilarity(a,b){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 1;if((A.includes(B)||B.includes(A))&&Math.min(A.length,B.length)>=7)return .9;return overlap(A,B)}
function matchProjects(memo,projects){const m=norm(memo);return projects.map(p=>{const name=clean(p.name),hay=[name,p.customer,p.manual_category||p.source_category,p.summary].map(clean).join(' ');let score=overlap(m,hay);if(name&&m.includes(norm(name)))score+=2;return {name,score}}).filter(x=>x.name&&x.score>0).sort((a,b)=>b.score-a.score).slice(0,5).map(x=>x.name)}
async function agentContext(token){const [projects,facts,sources,tasks]=await Promise.all([central.list(token,'Projects').catch(()=>[]),central.list(token,'ProductFacts').catch(()=>[]),sheetRows(token,'Sources','A1:O5000'),sheetRows(token,'Tasks','A1:L5000')]);const validIds=new Set(sources.map(s=>clean(s.source_id)).filter(Boolean)),lines=[];for(const p of projects.slice(0,120))lines.push(`[PROJECT] ${clean(p.name)} | 고객:${clean(p.customer)} | 상태:${clean(p.manual_status||p.source_status)} | 분류:${clean(p.manual_category||p.source_category)} | 요약:${clean(p.summary)} | 근거:${clean(p.source_evidence)} | sourceIds:${clean(p.source_ids)}`);for(const f of facts.slice(0,300))lines.push(`[FACT] ${clean(f.subject)} | ${clean(f.fact)} | 근거:${clean(f.evidence)} | sourceIds:${clean(f.source_ids)}`);for(const t of tasks.slice(0,500))lines.push(`[EXISTING_TASK] ${clean(t.title)} | 프로젝트:${clean(t.project)} | 담당자:${clean(t.owner)} | 기한:${clean(t.due_date)} | 상태:${clean(t.status)} | sourceIds:${clean(t.source_ids)}`);return {text:lines.join('\n').slice(0,120000),validIds,sourceCount:sources.length,existingTaskCount:tasks.length,projects,tasks}}
function normalizeAgentTasks(data,ctx){return arr(data?.tasks).map(t=>({title:clean(t.title),project:clean(t.project),owner:clean(t.owner),dueDate:clean(t.dueDate),status:clean(t.status)||'예정',reason:clean(t.reason),sourceEvidence:clean(t.sourceEvidence),sourceIds:arr(t.sourceIds).map(clean).filter(id=>ctx.validIds.has(id)),duplicateStatus:clean(t.duplicateStatus)||'new'})).filter(t=>t.title)}
function deterministicDuplicateCheck(tasks,ctx){const kept=[],checks=[],suppressed=[];for(const t of tasks){let best=null,bestScore=0;for(const e of ctx.tasks){const score=taskSimilarity(t.title,e.title);const sameProject=!t.project||!e.project||norm(t.project)===norm(e.project);if(sameProject&&score>bestScore){bestScore=score;best=e}}if(best&&bestScore>=.72){suppressed.push(t);checks.push(`${t.title} → 기존 '${clean(best.title)}'와 중복 가능성 ${(bestScore*100).toFixed(0)}% · 제외`)}else{kept.push({...t,duplicateStatus:'new'});checks.push(`${t.title} → 기존 업무와 유의미한 중복 없음 · 신규`)}}return {kept,checks,suppressed}}
async function callAdkAgent(memo,ctx){const baseUrl=String(process.env.TEAMGRIT_AGENT_URL||'').replace(/\/$/,'');if(!baseUrl)throw new Error('agent_runtime_not_configured');const headers={'Content-Type':'application/json'};if(process.env.TEAMGRIT_AGENT_TOKEN)headers.Authorization=`Bearer ${process.env.TEAMGRIT_AGENT_TOKEN}`;const r=await fetch(`${baseUrl}/teamgrit/analyze`,{method:'POST',headers,body:JSON.stringify({memo,centralContext:ctx.text,validSourceIds:[...ctx.validIds]})});if(!r.ok)throw new Error(`ADK runtime ${r.status}: ${(await r.text()).slice(0,400)}`);return r.json()}
async function runBuiltInAgent(memo,ctx,matchedProjects){const prompt=`너는 TeamGRIT 업무 에이전트다. 단순 요약기가 아니라 다음 순서로 판단한다: 1) 메모에서 실행 가능한 업무를 분해한다. 2) 중앙 PROJECT/FACT/SOURCE 근거와 연결한다. 3) EXISTING_TASK와 의미가 겹치면 duplicateStatus를 duplicate로 표시한다. 4) 근거가 없는 프로젝트/담당자/기한은 추정하지 않고 빈 문자열로 둔다. 5) 실행 가능한 신규 업무만 명확하게 제안한다. sourceIds는 실제 제공된 sourceIds만 사용한다. JSON만 반환한다. 형식: {"tasks":[{"title":string,"project":string,"owner":string,"dueDate":string,"status":string,"reason":string,"sourceEvidence":string,"sourceIds":[string],"duplicateStatus":"new"|"duplicate"}],"trace":{"reasoningSummary":string}}.\n\n[사용자 메모]\n${memo}\n\n[사전 매칭 프로젝트]\n${matchedProjects.join(', ')||'없음'}\n\n[중앙 최신 근거]\n${ctx.text}`;const ai=await gemini(prompt);return {...ai.data,modelUsed:ai.modelUsed}}
async function analyzeWithFallback(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const b=await readBody(req),memo=clean(b.memo);if(!memo)return json(res,400,{error:'memo_required'});const ctx=await agentContext(token);if(!ctx.text)return json(res,200,{tasks:[],modelUsed:null,error:'중앙 원본 근거가 아직 없습니다. 먼저 프로젝트 원본을 동기화해주세요.'});const matchedProjects=matchProjects(memo,ctx.projects);let data=null,runtime='google-adk',fallbackReason='';try{data=await callAdkAgent(memo,ctx)}catch(e){fallbackReason=String(e?.message||e);runtime='teamgrit-agent';data=await runBuiltInAgent(memo,ctx,matchedProjects)}const normalized=normalizeAgentTasks(data,ctx),aiDuplicates=normalized.filter(t=>t.duplicateStatus==='duplicate'),candidates=normalized.filter(t=>t.duplicateStatus!=='duplicate'),dup=deterministicDuplicateCheck(candidates,ctx),tasks=dup.kept,suppressedCount=aiDuplicates.length+dup.suppressed.length;const trace={matchedProjects,existingTaskChecks:dup.checks,proposedCount:tasks.length,suppressedDuplicateCount:suppressedCount,sourceCount:ctx.sourceCount,existingTaskCount:ctx.existingTaskCount,reasoningSummary:clean(data?.trace?.reasoningSummary),steps:[{name:'메모 분석',status:'완료',detail:`실행 후보 ${normalized.length}개 추출`},{name:'프로젝트·근거 매칭',status:'완료',detail:`프로젝트 ${matchedProjects.length}개 · Source ${ctx.sourceCount}개 확인`},{name:'기존 업무 비교',status:'완료',detail:`기존 Tasks ${ctx.existingTaskCount}개와 비교 · 중복 ${suppressedCount}개 제외`},{name:'신규 업무 제안',status:'완료',detail:`등록 검토 대상 ${tasks.length}개 생성`} ]};return json(res,200,{tasks,trace,modelUsed:data?.modelUsed||process.env.TEAMGRIT_AGENT_MODEL||'gemini-3.8-flash',runtime,agentRuntime:true,externalAdk:runtime==='google-adk',fallbackReason:runtime==='teamgrit-agent'?fallbackReason:'',sourceCount:ctx.sourceCount,existingTaskCount:ctx.existingTaskCount,usingCentralCache:true})}
module.exports=async(req,res)=>{try{const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action');if(req.method==='POST'&&action==='delete')return await deleteTask(req,res);if(req.method==='POST'&&action==='update')return await updateTask(req,res);if(req.method==='POST'&&action==='analyze')return await analyzeWithFallback(req,res);return base(req,res)}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}};
