require('./_lib/gemini-model-compat')();
const base=require('./tasks');
const central=require('./_lib/central-entities');
const {gemini,clean,arr}=require('./_lib/source-corpus-all');
const OPS=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';
const TASK_HEADERS=['task_id','title','project','owner','due_date','status','source','source_url','source_ids','created_at','approved_at','updated_at'];
function cookies(req){const o={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return o}
async function access(req){const c=cookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:c.g_refresh,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('Google token refresh failed');return (await r.json()).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function deleteTask(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req),id=String(b.task_id||b.id||'').trim();if(!id)return json(res,400,{error:'task_id_required'});const range=encodeURIComponent('Tasks!A1:L5000'),d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}`),rows=d.values||[];if(rows.length<2)return json(res,404,{error:'task_not_found'});const head=rows[0],kept=[head,...rows.slice(1).filter(r=>String(r[0]||'').trim()!==id)];if(kept.length===rows.length)return json(res,404,{error:'task_not_found'});await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}:clear`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent('Tasks!A1:L'+kept.length)}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:kept})});return json(res,200,{ok:true,deleted:id});}
async function updateTask(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected'});const b=await readBody(req),id=String(b.task_id||b.id||'').trim();if(!id)return json(res,400,{error:'task_id_required'});const range=encodeURIComponent('Tasks!A1:L5000'),d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${range}`),rows=d.values||[];if(rows.length<2)return json(res,404,{error:'task_not_found'});const head=rows[0].length?rows[0]:TASK_HEADERS,rowIndex=rows.slice(1).findIndex(r=>String(r[0]||'').trim()===id);if(rowIndex<0)return json(res,404,{error:'task_not_found'});const current={};head.forEach((h,i)=>current[h]=rows[rowIndex+1]?.[i]??'');const allowed={title:b.title,project:b.project,owner:b.owner,due_date:b.due_date??b.dueDate,status:b.status};for(const [k,v] of Object.entries(allowed))if(v!==undefined)current[k]=String(v).trim();current.updated_at=new Date().toISOString();const values=TASK_HEADERS.map(h=>current[h]??''),sheetRow=rowIndex+2;await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent(`Tasks!A${sheetRow}:L${sheetRow}`)}?valueInputOption=RAW`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({values:[values]})});return json(res,200,{ok:true,task:current});}
async function sheetRows(token,name,range){const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent(`${name}!${range}`)}`).catch(()=>({values:[]})),rows=d.values||[];if(rows.length<2)return[];const head=rows[0];return rows.slice(1).filter(r=>r.some(v=>String(v||'').trim())).map(r=>{const o={};head.forEach((h,i)=>o[h]=r[i]??'');return o})}
async function agentContext(token){const [projects,facts,sources,tasks]=await Promise.all([central.list(token,'Projects').catch(()=>[]),central.list(token,'ProductFacts').catch(()=>[]),sheetRows(token,'Sources','A1:O5000'),sheetRows(token,'Tasks','A1:L5000')]);const validIds=new Set(sources.map(s=>clean(s.source_id)).filter(Boolean)),lines=[];for(const p of projects.slice(0,120))lines.push(`[PROJECT] ${clean(p.name)} | 고객:${clean(p.customer)} | 상태:${clean(p.manual_status||p.source_status)} | 분류:${clean(p.manual_category||p.source_category)} | 요약:${clean(p.summary)} | 근거:${clean(p.source_evidence)} | sourceIds:${clean(p.source_ids)}`);for(const f of facts.slice(0,300))lines.push(`[FACT] ${clean(f.subject)} | ${clean(f.fact)} | 근거:${clean(f.evidence)} | sourceIds:${clean(f.source_ids)}`);for(const t of tasks.slice(0,500))lines.push(`[EXISTING_TASK] ${clean(t.title)} | 프로젝트:${clean(t.project)} | 담당자:${clean(t.owner)} | 기한:${clean(t.due_date)} | 상태:${clean(t.status)} | sourceIds:${clean(t.source_ids)}`);return {text:lines.join('\n').slice(0,120000),validIds,sourceCount:sources.length,existingTaskCount:tasks.length}}
function normalizeAgentTasks(data,ctx){return arr(data?.tasks).map(t=>({title:clean(t.title),project:clean(t.project),owner:clean(t.owner),dueDate:clean(t.dueDate),status:clean(t.status),reason:clean(t.reason),sourceEvidence:clean(t.sourceEvidence),sourceIds:arr(t.sourceIds).map(clean).filter(id=>ctx.validIds.has(id)),duplicateStatus:clean(t.duplicateStatus)||'new'})).filter(t=>t.title&&t.duplicateStatus!=='duplicate')}
async function callAdkAgent(memo,ctx){const baseUrl=String(process.env.TEAMGRIT_AGENT_URL||'').replace(/\/$/,'');if(!baseUrl)throw new Error('agent_runtime_not_configured');const headers={'Content-Type':'application/json'};if(process.env.TEAMGRIT_AGENT_TOKEN)headers.Authorization=`Bearer ${process.env.TEAMGRIT_AGENT_TOKEN}`;const r=await fetch(`${baseUrl}/teamgrit/analyze`,{method:'POST',headers,body:JSON.stringify({memo,centralContext:ctx.text,validSourceIds:[...ctx.validIds]})});if(!r.ok)throw new Error(`ADK runtime ${r.status}: ${(await r.text()).slice(0,400)}`);return r.json()}
async function analyzeWithFallback(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const b=await readBody(req),memo=clean(b.memo);if(!memo)return json(res,400,{error:'memo_required'});const ctx=await agentContext(token);if(!ctx.text)return json(res,200,{tasks:[],modelUsed:null,error:'중앙 원본 근거가 아직 없습니다. 먼저 프로젝트 원본을 동기화해주세요.'});let data=null,runtime='google-adk',fallbackReason='';try{data=await callAdkAgent(memo,ctx)}catch(e){fallbackReason=String(e?.message||e);runtime='gemini-fallback';const prompt=`TeamGRIT 업무 후보 생성기다. 사용자 메모와 중앙에 이미 동기화된 실제 프로젝트/제품/기존 업무 근거만 사용한다. 근거에 없는 프로젝트, 담당자, 기한, 상태는 추정하지 말고 빈 문자열로 둔다. EXISTING_TASK와 중복되는 업무는 반환하지 않는다. sourceIds는 제공된 근거의 sourceIds만 사용한다. JSON만 반환: {"tasks":[{"title":string,"project":string,"owner":string,"dueDate":string,"status":string,"reason":string,"sourceEvidence":string,"sourceIds":[string],"duplicateStatus":"new"}],"trace":{"matchedProjects":[string],"existingTaskChecks":[string],"proposedCount":number,"suppressedDuplicateCount":number}}.\n\n[사용자 메모]\n${memo}\n\n[중앙 최신 근거]\n${ctx.text}`;const ai=await gemini(prompt);data={...ai.data,modelUsed:ai.modelUsed}}
const tasks=normalizeAgentTasks(data,ctx),trace=data?.trace||{};return json(res,200,{tasks,trace:{...trace,proposedCount:tasks.length},modelUsed:data?.modelUsed||process.env.TEAMGRIT_AGENT_MODEL||'gemini-3.8-flash',runtime,agentRuntime:runtime==='google-adk',fallbackReason:runtime==='gemini-fallback'?fallbackReason:'',sourceCount:ctx.sourceCount,existingTaskCount:ctx.existingTaskCount,usingCentralCache:true})}
module.exports=async(req,res)=>{try{const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action');if(req.method==='POST'&&action==='delete')return await deleteTask(req,res);if(req.method==='POST'&&action==='update')return await updateTask(req,res);if(req.method==='POST'&&action==='analyze')return await analyzeWithFallback(req,res);return base(req,res)}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}};
