require('./_lib/gemini-model-compat')();
const base=require('./tasks-v2');
const central=require('./_lib/central-entities');
const {gemini,clean,arr}=require('./_lib/source-corpus-all');

const OPS=process.env.OPS_DATA_SHEET_ID||'1Gfs2mC9_b7_u7sGIDC74WD-GUTLJy8JqBhSXwlzN_Uk';

function cookies(req){const o={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return o}
async function access(req){const c=cookies(req);if(c.g_access)return c.g_access;if(!c.g_refresh)return null;const p=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID||'',client_secret:process.env.GOOGLE_CLIENT_SECRET||'',refresh_token:c.g_refresh,grant_type:'refresh_token'}),r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});if(!r.ok)throw new Error('Google token refresh failed');return (await r.json()).access_token}
async function gf(token,url,opts={}){const r=await fetch(url,{...opts,headers:{Authorization:`Bearer ${token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(`Google API ${r.status}: ${(await r.text()).slice(0,500)}`);return (r.headers.get('content-type')||'').includes('json')?r.json():r.text()}
async function readBody(req){let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return {}}}
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data))}
async function sheetRows(token,name,range){const d=await gf(token,`https://sheets.googleapis.com/v4/spreadsheets/${OPS}/values/${encodeURIComponent(`${name}!${range}`)}`).catch(()=>({values:[]})),rows=d.values||[];if(rows.length<2)return[];const head=rows[0];return rows.slice(1).filter(r=>r.some(v=>String(v||'').trim())).map(r=>{const o={};head.forEach((h,i)=>o[h]=r[i]??'');return o})}
function norm(v){return clean(v).toLowerCase().replace(/[^a-z0-9가-힣]+/g,' ').replace(/\s+/g,' ').trim()}
function toks(v){return [...new Set(norm(v).split(' ').filter(x=>x.length>=2))]}
function overlap(a,b){const A=toks(a),B=new Set(toks(b));if(!A.length||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(A.length,B.size)}
function taskSimilarity(a,b){const A=norm(a),B=norm(b);if(!A||!B)return 0;if(A===B)return 1;if((A.includes(B)||B.includes(A))&&Math.min(A.length,B.length)>=7)return .9;return overlap(A,B)}
function ids(v){return [...new Set(String(v||'').split(/[\s,;|]+/).map(clean).filter(Boolean))]}
function sourceId(s){return clean(s.source_id||s.sourceId||s.id)}
function sourceTitle(s){return clean(s.title||s.name||s.file_name||s.fileName||sourceId(s))}
function sourceText(s){return Object.values(s||{}).map(clean).filter(Boolean).join(' ')}
function projectText(p){return [p.name,p.customer,p.manual_category,p.source_category,p.summary,p.source_evidence,p.evidence].map(clean).join(' ')}
function projectSourceIds(p){return ids(p.source_ids||p.sourceIds)}
function factText(f){return [f.subject,f.fact,f.evidence].map(clean).join(' ')}
function factSourceIds(f){return ids(f.source_ids||f.sourceIds)}
function score(query,text){const q=norm(query),t=norm(text);if(!q||!t)return 0;let s=overlap(q,t);for(const token of toks(q)){if(token.length>=4&&t.includes(token))s+=.035}return s}
function rank(query,items,textFn,limit=20,min=.03){return items.map(item=>({item,score:score(query,textFn(item))})).filter(x=>x.score>=min).sort((a,b)=>b.score-a.score).slice(0,limit)}
function sourceMap(sources){const m=new Map();for(const s of sources){const id=sourceId(s);if(id)m.set(id,s)}return m}
function exactProject(projects,name){const n=norm(name);return projects.find(p=>norm(p.name)===n)||null}
function buildFocusedContext(memo,projects,facts,sources,tasks){
  const rankedProjects=rank(memo,projects,projectText,8,.025);
  const rankedFacts=rank(memo,facts,factText,40,.025);
  const wanted=new Set();
  for(const x of rankedProjects)for(const id of projectSourceIds(x.item))wanted.add(id);
  for(const x of rankedFacts)for(const id of factSourceIds(x.item))wanted.add(id);
  const rankedSources=rank(memo,sources,sourceText,25,.02);
  for(const x of rankedSources)wanted.add(sourceId(x.item));
  const relatedSources=sources.filter(s=>wanted.has(sourceId(s))).slice(0,40);
  const relatedTasks=rank(memo,tasks,t=>[t.title,t.project,t.owner,t.source].map(clean).join(' '),60,.015).map(x=>x.item);
  const lines=[];
  for(const x of rankedProjects)lines.push(`[PROJECT] ${clean(x.item.name)} | score:${x.score.toFixed(3)} | 고객:${clean(x.item.customer)} | 상태:${clean(x.item.manual_status||x.item.source_status)} | 분류:${clean(x.item.manual_category||x.item.source_category)} | 요약:${clean(x.item.summary)} | 근거:${clean(x.item.source_evidence||x.item.evidence)} | sourceIds:${projectSourceIds(x.item).join(',')}`);
  for(const x of rankedFacts)lines.push(`[FACT] ${clean(x.item.subject)} | ${clean(x.item.fact)} | score:${x.score.toFixed(3)} | 근거:${clean(x.item.evidence)} | sourceIds:${factSourceIds(x.item).join(',')}`);
  for(const s of relatedSources)lines.push(`[SOURCE] ${sourceId(s)} | ${sourceTitle(s)} | ${clean(s.root_source||s.rootSource)} | ${clean(s.url||s.source_url||s.webViewLink)}`);
  for(const t of relatedTasks)lines.push(`[EXISTING_TASK] ${clean(t.title)} | 프로젝트:${clean(t.project)} | 담당자:${clean(t.owner)} | 기한:${clean(t.due_date)} | 상태:${clean(t.status)} | sourceIds:${clean(t.source_ids)}`);
  return {text:lines.join('\n').slice(0,120000),rankedProjects,rankedFacts,relatedSources,relatedTasks};
}
async function context(token,memo){const [projects,facts,sources,tasks]=await Promise.all([central.list(token,'Projects').catch(()=>[]),central.list(token,'ProductFacts').catch(()=>[]),sheetRows(token,'Sources','A1:O5000'),sheetRows(token,'Tasks','A1:L5000')]);const validIds=new Set(sources.map(sourceId).filter(Boolean)),focused=buildFocusedContext(memo,projects,facts,sources,tasks);return {projects,facts,sources,tasks,validIds,sourceById:sourceMap(sources),focused,totalSourceCount:sources.length,existingTaskCount:tasks.length}}
function normalizeTasks(data,ctx){return arr(data?.tasks).map(t=>({title:clean(t.title),project:clean(t.project),owner:clean(t.owner),dueDate:clean(t.dueDate),status:clean(t.status)||'예정',reason:clean(t.reason),sourceEvidence:clean(t.sourceEvidence),sourceIds:arr(t.sourceIds).map(clean).filter(id=>ctx.validIds.has(id)),duplicateStatus:clean(t.duplicateStatus)||'new'})).filter(t=>t.title)}
function resolveProject(task,ctx,memo){const knownAi=exactProject(ctx.projects,task.project);let best=null,bestScore=0,bestReason='';const taskQuery=[task.title,task.reason,task.sourceEvidence].join(' '),taskIds=new Set(task.sourceIds||[]);for(const p of ctx.projects){const pIds=projectSourceIds(p),shared=pIds.filter(id=>taskIds.has(id));let s=score(taskQuery,projectText(p));if(shared.length)s+=2+Math.min(1,shared.length*.25);if(knownAi&&norm(knownAi.name)===norm(p.name))s+=.35;if(norm(memo).includes(norm(p.name))&&norm(p.name).length>=4)s+=.4;if(s>bestScore){best=p;bestScore=s;bestReason=shared.length?`후보 근거 Source ${shared.slice(0,3).join(', ')}가 프로젝트 근거와 연결됨`:`업무 문맥과 프로젝트 근거 유사도 ${s.toFixed(2)}`}}
  if(!best||bestScore<.16)return {project:'',projectEvidence:'명확한 프로젝트 근거를 찾지 못해 확인 필요',projectScore:bestScore};
  return {project:clean(best.name),projectEvidence:bestReason,projectScore:bestScore};
}
function enrichTask(task,ctx,memo){const rp=resolveProject(task,ctx,memo),titles=(task.sourceIds||[]).map(id=>({id,title:sourceTitle(ctx.sourceById.get(id)||{}),url:clean((ctx.sourceById.get(id)||{}).url||(ctx.sourceById.get(id)||{}).source_url)}));return {...task,...rp,sourceTitles:titles,decisionSummary:`${rp.project?`프로젝트 '${rp.project}' 근거 확인`:'프로젝트 확인 필요'} · Source ${titles.length}개 근거 사용`}}
function duplicateCheck(tasks,ctx){const kept=[],checks=[],suppressed=[];for(const t of tasks){let best=null,bestScore=0;for(const e of ctx.tasks){const s=taskSimilarity(t.title,e.title),sameProject=!t.project||!e.project||norm(t.project)===norm(e.project);if(sameProject&&s>bestScore){best=e;bestScore=s}}if(best&&bestScore>=.72){suppressed.push(t);checks.push({title:t.title,result:'duplicate',matchedTask:clean(best.title),score:bestScore})}else{kept.push({...t,duplicateStatus:'new'});checks.push({title:t.title,result:'new',matchedTask:'',score:bestScore})}}return {kept,checks,suppressed}}
async function callAdk(memo,ctx){const baseUrl=String(process.env.TEAMGRIT_AGENT_URL||'').replace(/\/$/,'');if(!baseUrl)throw new Error('agent_runtime_not_configured');const headers={'Content-Type':'application/json'};if(process.env.TEAMGRIT_AGENT_TOKEN)headers.Authorization=`Bearer ${process.env.TEAMGRIT_AGENT_TOKEN}`;const r=await fetch(`${baseUrl}/teamgrit/analyze`,{method:'POST',headers,body:JSON.stringify({memo,centralContext:ctx.focused.text,validSourceIds:[...ctx.validIds]})});if(!r.ok)throw new Error(`ADK runtime ${r.status}: ${(await r.text()).slice(0,400)}`);return r.json()}
async function runBuiltIn(memo,ctx){const projectNames=ctx.focused.rankedProjects.map(x=>clean(x.item.name));const prompt=`너는 TeamGRIT 업무 에이전트다. 아래는 전체 회사 자료가 아니라 사용자 메모와 관련도가 높은 중앙 근거만 선별한 컨텍스트다. 반드시 이 근거 안에서만 판단한다.\n1) 메모를 실행 가능한 업무로 분해한다.\n2) 관련 PROJECT/FACT/SOURCE를 근거로 연결한다.\n3) project는 반드시 제공된 PROJECT의 정확한 이름만 사용하거나, 불명확하면 빈 문자열로 둔다.\n4) 담당자/기한도 메모 또는 근거에 명시되지 않으면 빈 문자열로 둔다.\n5) sourceIds는 제공된 SOURCE/PROJECT/FACT에 실제 등장한 ID만 사용한다.\n6) 기존 업무와 겹치면 duplicateStatus=duplicate.\nJSON만 반환한다. 형식: {"tasks":[{"title":string,"project":string,"owner":string,"dueDate":string,"status":string,"reason":string,"sourceEvidence":string,"sourceIds":[string],"duplicateStatus":"new"|"duplicate"}],"trace":{"reasoningSummary":string}}.\n\n[사용자 메모]\n${memo}\n\n[사용 가능한 프로젝트명]\n${projectNames.join('\n')||'없음'}\n\n[관련 중앙 근거]\n${ctx.focused.text}`;const ai=await gemini(prompt);return {...ai.data,modelUsed:ai.modelUsed}}
async function analyze(req,res){const token=await access(req);if(!token)return json(res,401,{error:'google_not_connected',connection:'연결 안 됨'});const b=await readBody(req),memo=clean(b.memo);if(!memo)return json(res,400,{error:'memo_required'});const ctx=await context(token,memo);if(!ctx.focused.text)return json(res,200,{tasks:[],modelUsed:null,error:'관련 중앙 근거를 찾지 못했습니다. 먼저 원본을 동기화하거나 메모를 더 구체적으로 작성해주세요.'});let data,runtime='google-adk',fallbackReason='';try{data=await callAdk(memo,ctx)}catch(e){runtime='teamgrit-agent';fallbackReason=String(e?.message||e);data=await runBuiltIn(memo,ctx)}const normalized=normalizeTasks(data,ctx).map(t=>enrichTask(t,ctx,memo)),aiDup=normalized.filter(t=>t.duplicateStatus==='duplicate'),candidates=normalized.filter(t=>t.duplicateStatus!=='duplicate'),dup=duplicateCheck(candidates,ctx),tasks=dup.kept,suppressed=aiDup.length+dup.suppressed.length,usedIds=[...new Set(tasks.flatMap(t=>t.sourceIds||[]))],matchedProjects=[...new Set(tasks.map(t=>t.project).filter(Boolean))];const trace={matchedProjects,relevantSourceCount:ctx.focused.relatedSources.length,usedSourceCount:usedIds.length,totalSourceCount:ctx.totalSourceCount,existingTaskChecks:dup.checks,proposedCount:tasks.length,suppressedDuplicateCount:suppressed,existingTaskCount:ctx.existingTaskCount,reasoningSummary:clean(data?.trace?.reasoningSummary),relevantSources:ctx.focused.relatedSources.slice(0,12).map(s=>({id:sourceId(s),title:sourceTitle(s),url:clean(s.url||s.source_url)})),steps:[{name:'관련 근거 검색',status:'완료',detail:`전체 Source ${ctx.totalSourceCount}개 중 관련 Source ${ctx.focused.relatedSources.length}개 선별`},{name:'프로젝트 확정',status:'완료',detail:`근거 연결로 프로젝트 ${matchedProjects.length}개 확정`},{name:'기존 업무 비교',status:'완료',detail:`기존 Tasks ${ctx.existingTaskCount}개와 비교 · 중복 ${suppressed}개 제외`},{name:'신규 업무 제안',status:'완료',detail:`실제 판단에 Source ${usedIds.length}개 사용 · 신규 ${tasks.length}개 제안`} ]};return json(res,200,{tasks,trace,modelUsed:data?.modelUsed||process.env.TEAMGRIT_AGENT_MODEL||'gemini-3.8-flash',runtime,agentRuntime:true,externalAdk:runtime==='google-adk',fallbackReason:runtime==='teamgrit-agent'?fallbackReason:'',sourceCount:ctx.totalSourceCount,relevantSourceCount:ctx.focused.relatedSources.length,usedSourceCount:usedIds.length,existingTaskCount:ctx.existingTaskCount,usingCentralCache:true})}
module.exports=async(req,res)=>{try{const u=new URL(req.url,`https://${req.headers.host}`),action=u.searchParams.get('action');if(req.method==='POST'&&action==='analyze')return await analyze(req,res);return base(req,res)}catch(e){return json(res,500,{error:e.message,connection:'연결 안 됨'})}};
